<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$page_name = Help::CONTEXT_MENU_HELP;
$help = new Help();
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $page_name]); ?>

<p>
    <?= I18N::translate('In the General Settings section, there is an option in the Browser options that lets you choose what happens when you click on an individual in the diagram. One of the options is to show a menu, and the menu has the following options:'); ?>
</p>
<ul>
    <li><?= I18N::translate('Open individual\'s page'); ?> -<?= I18N::translate('When you click on an individual, the webtrees page for that individual will open in a new tab or window.'); ?></li>
    <li><?= I18N::translate('Add individual to list of starting individuals'); ?> - <?= I18N::translate('If this option is selected, clicking on an individual in the diagram will add them to the list of starting individuals.'); ?></li>
    <li><?= I18N::translate('Replace starting individuals with this individual'); ?> - <?= I18N::translate('If this option is selected, clicking on an individual in the diagram will add them to the list of starting individuals and remove all others from the list.'); ?></li>
    <li><?= I18N::translate('Add this individual to the list of stopping individuals'); ?> - <?= I18N::translate('If this option is selected, clicking on an individual in the diagram will add them to the list of stopping individuals.'); ?></li>
    <li><?= I18N::translate('Replace stopping individuals with this individual'); ?> - <?= I18N::translate('If this option is selected, clicking on an individual in the diagram will add them to the list of stopping individuals and remove all others from the list.'); ?></li>
    <li><?= I18N::translate('Add to list of individuals to highlight'); ?> - <?= I18N::translate('If this option is selected, clicking on an individual in the diagram will add them to the list of individuals with a coloured background for identification in the diagram. See the option "Show selected individuals in different colour", in the Colours section of the Tile design options.'); ?></li>
</ul>

<p>
    <?= I18N::translate('Related links'); ?>:
</p>
<ul>
    <li><?= $help->getHelpLinkHtml(HELP::XREFs_OF_INDIVIDUALS);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::STOP_PROCESSING_ON);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::TILE_DESIGN);?></li>
</ul>