<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$page_name = Help::CLIPPINGS_CART;
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $page_name]); ?>

<p>
    <?= I18N::translate('Within webtrees, you can add items to the clippings cart. This is usually done by navigating to a record within webtrees then selecting the &quot;Clippings cart&quot; option near the top of the screen.</p><p> If you have added individuals and the related family and media records to the clippings cart, these can be used to display the diagram instead of the criteria in the &quot;People to be included&quot; section.</p><p>If you have individuals in the clippings cart but don&apos;t wish to use these, you have the option to ignore the clippings cart.'); ?>
</p>