<?php
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use vendor\WebtreesModules\gvexport\GVExport;use vendor\WebtreesModules\gvexport\MainPage;

/**
 * @var array       $vars           array of saved settings
 * @var Tree        $tree           webtrees tree object of current tree
 * @var GVExport    $module         this module
 * @var array       $settings       wider array of settings and options
 * @var Individual  $individual     Individual object from webtrees
 */

?>

<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/Appearance/GraphDirection',['vars' => $vars, 'settings' => $settings, 'show_help' => true]); ?>
</div>

<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/Appearance/DiagramType',['vars' => $vars, 'show_help' => true]); ?>
</div>

<div id="appearance-advanced" <?= $vars["show_adv_appear"] ? '' : 'style="display:none"' ?>>

    <?php if ($tree->getPreference('SHOW_HIGHLIGHT_IMAGES') == '1') { ?>
        <div class="row no-right-margin form-group">
            <?= view($module->name() . '::MainPage/Appearance/Photos',['vars' => $vars, 'settings' => $settings, 'show_help' => true]); ?>
        </div>
    <?php } ?>

    <div class="row no-right-margin form-group">
        <?= view($module->name() . '::MainPage/Appearance/TileDesign',['vars' => $vars, 'settings' => $settings, 'show_help' => true]); ?>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('add_links', 'Add URL to individuals and families'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <input type="checkbox" name="vars[add_links]" id="add_links" value="add_links" <?= $vars["add_links"] ? 'checked' : '' ?>>
            <span class="text-muted">(<?= $usegraphviz ? I18N::translate('browser, SVG, and PDF only') : I18N::translate('browser and SVG only'); ?>)</span>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('use_abbr_name', 'Abbreviated names'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <?= view('components/select', ['name' => 'vars[use_abbr_name]', 'id' => 'use_abbr_name', 'selected' => I18N::digits($vars['use_abbr_name']), 'options' => MainPage::updateTranslations($settings["use_abbr_names"])]) ?>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('use_abbr_place', 'Abbreviated place names'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <?= view('components/select', ['name' => 'vars[use_abbr_place]', 'id' => 'use_abbr_place', 'selected' => I18N::digits($vars['use_abbr_place']), 'options' => MainPage::updateTranslations($settings["use_abbr_places"])]) ?>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('show_xref_individuals', 'Show individual XREF'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <?php
            /* Check if another module (e.g. vesta classic) is adding the XREF to
               the name. If so, we want to enable the XREF option for individuals
               unless we already have a saved setting */
            $startName = $individual->fullName();
            $name = str_replace(" (" . $individual->xref() . ")", "", $startName);
            if ($startName != $name && isset($vars["first_run_xref_check"])) {
                $overridePID = true;
            } else {
                $overridePID = false;
            }
            ?>
            <input type="checkbox" name="vars[show_xref_individuals]" id="show_xref_individuals" value="show_xref_individuals" <?= $vars["show_xref_individuals"] || $overridePID ? 'checked' : '' ?>>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('show_birthdate', 'Show birth date'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <div class="row">
                <div class="col-auto mx-3">
                    <input type="checkbox" name="vars[show_birthdate]" id="show_birthdate" value="show_birthdate" <?= $vars["show_birthdate"] ? 'checked' : '' ?>>
                </div>
                <div class="col-auto mx-3">
                    <input type="radio" name="vars[birthdate_year_only]" id="bd_type_y" value="true" <?= $vars["birthdate_year_only"] ? 'checked' : '' ?>>
                    <label for="bd_type_y"><?= I18N::translate('Year') ?></label>
                </div>
                <div class="col-auto mx-3">
                    <input type="radio" name="vars[birthdate_year_only]" id="bd_type_gedcom" value="false" <?= !$vars["birthdate_year_only"] ? 'checked' : '' ?>>
                    <label for="bd_type_gedcom"><?= I18N::translate('Full date') ?></label>
                </div>
            </div>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('show_birthplace', 'Show birth place'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <input type="checkbox" name="vars[show_birthplace]" id="show_birthplace" value="show_birthplace" <?= $vars["show_birthplace"] ? 'checked' : '' ?>>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('show_death_date', 'Show death date'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <div class="row">
                <div class="col-auto mx-3">
                    <input type="checkbox" name="vars[show_death_date]" id="show_death_date" value="show_death_date" <?= $vars["show_death_date"] ? 'checked' : '' ?>>
                </div>
                <div class="col-auto mx-3">
                    <input type="radio" name="vars[death_date_year_only]" id="dd_type_y" value="true" <?= $vars["death_date_year_only"] ? 'checked' : '' ?>>
                    <label for="dd_type_y"><?= I18N::translate('Year') ?></label>
                </div>
                <div class="col-auto mx-3">
                    <input type="radio" name="vars[death_date_year_only]" id="dd_type_gedcom" value="false" <?= !$vars["death_date_year_only"] ? 'checked' : '' ?>>
                    <label for="dd_type_gedcom"><?= I18N::translate('Full date') ?></label>
                </div>
            </div>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('show_death_place', 'Show death place'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <input type="checkbox" name="vars[show_death_place]" id="show_death_place" value="show_death_place" <?= $vars["show_death_place"] ? 'checked' : '' ?>>
        </div>
    </div>


    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('show_xref_families', 'Show family XREF'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <input type="checkbox" name="vars[show_xref_families]" id="show_xref_families" value="show_xref_families" <?= $vars["show_xref_families"] ? 'checked' : '' ?>>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('show_marriage_date', 'Show marriage date'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <div class="row">
                <div class="col-auto mx-3">
                    <input type="checkbox" name="vars[show_marriage_date]" id="show_marriage_date" value="show_marriage_date" <?= $vars["show_marriage_date"] ? 'checked' : '' ?>>
                </div>
                <div class="col-auto mx-3">
                    <input type="radio" name="vars[marr_date_year_only]" id="md_type_y" value="true" <?= $vars["marr_date_year_only"] ? 'checked' : '' ?>>
                    <label for="md_type_y"><?= I18N::translate('Year') ?></label>
                </div>
                <div class="col-auto mx-3">
                    <input type="radio" name="vars[marr_date_year_only]" id="md_type_gedcom" value="false" <?= !$vars["marr_date_year_only"] ? 'checked' : '' ?>>
                    <label for="md_type_gedcom"><?= I18N::translate('Full date') ?></label>
                </div>
            </div>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('show_marriage_place', 'Show marriage place'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <input type="checkbox" name="vars[show_marriage_place]" id="show_marriage_place" value="show_marriage_place" <?= $vars["show_marriage_place"] ? 'checked' : '' ?>>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('dpi', 'DPI'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <div class="row">
                <div class="col-auto">
                    <input type="text" onblur="defaultValueWhenBlank(this, 72)" class="form-control" size="10" name="vars[dpi]" id="dpi"
                           value="<?= I18N::digits($vars["dpi"]); ?>">
                </div>
            </div>
        </div>
    </div>

    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('', 'Space'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <div class="row">
                <label for="ranksep"><?= I18N::translate('Between generations') ?></label>
                <div class="col-auto">
                    <input type="text" onclick="togglePercent(this, false)" onblur="togglePercent(this, true)" class="form-control col-sm-6" size="10" name="vars[ranksep]" id="ranksep"
                           value="<?= e($vars["ranksep"]) ?>">
                </div>
                <label for="nodesep"><?= I18N::translate('Between individuals on the same level') ?></label>
                <div class="col-auto">
                    <input type="text" onclick="togglePercent(this, false)" onblur="togglePercent(this, true)" class="form-control col-sm-6" size="10" name="vars[nodesep]" id="nodesep"
                           value="<?= e($vars["nodesep"]) ?>">
                </div>
            </div>
        </div>
    </div>
    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('', 'Relationship arrows'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <div class="col-auto">
                <input type="color" class="picker" name="vars[arrows_default]" id="arrows_default" value="<?= e($vars["arrows_default"]); ?>" /><label for="arrows_default" class="picker-label"><?= I18N::translate('Arrow color') ?></label>
            </div>
            <input type="checkbox" name="vars[colour_arrow_related]" onclick="showHide(document.getElementById('arrow_group'),this.checked)" id="colour_arrow_related" value="colour_arrow_related" <?= $vars["colour_arrow_related"] ? 'checked' : '' ?>><label for="colour_arrow_related" class="check-list"><?= I18N::translate('Show blood relationship in different color') ?></label>

            <div id="arrow_group" class="color_subgroup col-auto wt-page-options-value" <?= !$vars["colour_arrow_related"] ? 'style="display:none;"' : '' ?>>
                <div class="sub-group">
                    <input type="color" class="picker" name="vars[arrows_related]" id="arrows_related" value="<?= e($vars["arrows_related"]); ?>" /><label for="arrows_related" class="picker-label"><?= I18N::translate('Related by birth') ?></label>
                    <input type="color" class="picker" name="vars[arrows_not_related]" id="arrows_not_related" value="<?= e($vars["arrows_not_related"]); ?>" /><label for="arrows_not_related" class="picker-label"><?= I18N::translate('Related other than by birth') ?></label>
                </div>
            </div>
        </div>
    </div>
    <div class="row no-right-margin form-group">
        <?= MainPage::addLabel('', 'Other colours'); ?>
        <div class="col-sm-8 wt-page-options-value">
            <div class="col-auto">
                <input type="color" class="picker" name="vars[family_col]" id="family_col" value="<?= e($vars["family_col"]); ?>" /><label for="family_col" class="picker-label"><?= I18N::translate('Family background') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[border_col]" id="border_col" value="<?= e($vars["border_col"]); ?>" /><label for="border_col" class="picker-label"><?= I18N::translate('Outline colour') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[background_col]" id="background_col" value="<?= e($vars["background_col"]); ?>" /><label for="background_col" class="picker-label"><?= I18N::translate('Diagram background color') ?></label>
            </div>
        </div>
    </div>
</div>
<a id="appearance-advanced-button" onclick="toggleAdvanced(this, 'appearance-advanced')"><div class="wt-page-options-label advanced-settings-btn"><?= ($vars["show_adv_appear"] ? '↑ ' : '↓ ') . I18N::translate('Toggle advanced settings') . ($vars["show_adv_appear"] ? ' ↑' : ' ↓'); ?></div></a>