<?php

use Fisharebest\Webtrees\I18N;

?>
<script type="text/javascript">
    const TRANSLATE = {
    "Delete":"<?= I18N::translate('Delete'); ?>",
    "Download":"<?= I18N::translate('Download'); ?>",
    "Copy link":"<?= I18N::translate('Copy link'); ?>",
    "Revoke link":"<?= I18N::translate('Revoke link'); ?>",
    "Revoked access to shared link":"<?= I18N::translate('Revoked access to shared link'); ?>",
    "Copied link to clipboard":"<?= I18N::translate('Copied link to clipboard'); ?>",
    "Failed to copy link to clipboard":"<?= I18N::translate('Failed to copy link to clipboard'); ?>",
    "Copy manually below":"<?= I18N::translate('Copy manually below'); ?>",
    "Overwrite settings '%s'?":"<?= I18N::translate("Overwrite settings '%s'?", '%s'); ?>",
    "Add to My favourites":"<?= I18N::translate('Add to My favourites'); ?>",
    "Add to Tree favourites":"<?= I18N::translate('Add to Tree favourites'); ?>",
    "Added to My favourites":"<?= I18N::translate('Added to My favourites'); ?>",
    "Added to Tree favourites":"<?= I18N::translate('Added to Tree favourites'); ?>",
    "Source individual has replaced existing individual":"<?= I18N::translate('Source individual has replaced existing individual'); ?>",
    "One new source individual added to %s existing individuals":"<?= I18N::translate('One new source individual added to %s existing individuals', '%s'); ?>",
    "Cancel":"<?= I18N::translate('Cancel'); ?>",
    "Overwrite":"<?= I18N::translate('Overwrite'); ?>",
    "Individual not found":"<?= I18N::translate('Individual not found') ?>",
    "Diagram will be rendered in browser as server doesn't support photo shapes":"<?= I18N::translate("Diagram will be rendered in browser as server doesn't support photo shapes"); ?>",
    "Message history":"<?= I18N::translate('Message history'); ?>",
    "Your browser does not support exporting images this large. Please reduce number of records, reduce DPI setting, or use SVG option.":"<?= I18N::translate('Your browser does not support exporting images this large. Please reduce number of records, reduce DPI setting, or use SVG option.') ?>",
    "Unable to load setting":"<?= I18N::translate('Unable to load setting') ?>",
    "Invalid JSON":"<?= I18N::translate('Invalid JSON'); ?>",
    "Login expired. Reloading page...":"<?= I18N::translate('Login expired. Reloading page...'); ?>",
    "Update successful":"<?= I18N::translate('Update successful'); ?>",
    "Enter new setting name":"<?= I18N::translate('Enter new setting name'); ?>",
    "Rename":"<?= I18N::translate('Rename'); ?>",
    "No styles set based on shared notes.":"<?= I18N::translate('No styles set based on shared notes.'); ?>",
    "%s shared note styles saved.":"<?= I18N::translate('%s shared note styles saved.', '%s'); ?>",
    "Add individual to list of starting individuals":"<?= I18N::translate('Add individual to list of starting individuals'); ?>",
    "Open individual's page":"<?= I18N::translate('Open individual\'s page'); ?>",
    "Replace starting individuals with this individual":"<?= I18N::translate('Replace starting individuals with this individual'); ?>",
    "Add this individual to the list of stopping individuals":"<?= I18N::translate('Add this individual to the list of stopping individuals'); ?>",
    "Replace stopping individuals with this individual":"<?= I18N::translate('Replace stopping individuals with this individual'); ?>",
    "Add to list of individuals to highlight":"<?= I18N::translate('Add to list of individuals to highlight'); ?>",
    };
</script>