<?php

namespace vendor\WebtreesModules\gvexport;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;


/*
 * tbd: better documentation of all transferred variables
 */

/**
 * @var string      $gvexport_css           used in javascript code as a link to the css file
 * @var string      $gvexport_js            used in javascript code as a link to the external script file
 * @var Tree        $tree                   used tree
 * @var Individual  $individual             The webtrees individual object of the XREF in the URL
 * @var string      $title                  title of this page
 * @var array       $vars                   array of saved settings
 * @var array       $otypes                 output file type options
 * @var bool        $cartempty              are there any individuals (INDI records) in the clippings cart?
 * @var ?           $module                 this module
 */

$settings = (new Settings())->getDefaultSettings();
$usegraphviz = $vars['graphviz_bin'] != "";
$xref = $individual->xref();
?>

<script type="text/javascript">
    // stylesheet
    const newSheet = document.createElement("link");
    newSheet.setAttribute("rel","stylesheet");
    newSheet.setAttribute("type","text/css");
    newSheet.setAttribute("href","<?= $gvexport_css ?>");
    document.head.appendChild(newSheet);
    function runPageLoaded() {
        if (typeof pageLoaded === 'function' && typeof jQuery === 'function') {
            changeURLXref('<?= e($xref); ?>');
            pageLoaded();
        } else {
            // If external script loads before inline script, then wait
            // before trying to run page loaded function.
            setTimeout(runPageLoaded, 100);
        }
    }
    
    // Javascript functions
    const newScript = document.createElement("script");
    newScript.onload = function() {
        // Check that a) our function that runs on page load has been loaded, and
        // b), jQuery exists (as this comes via webtrees)
        runPageLoaded();
    };
    newScript.setAttribute("type","text/javascript");
    newScript.setAttribute("src","<?= $gvexport_js ?>");
    document.head.appendChild(newScript);
</script>
<script src="<?= $module->assetUrl('javascript/viz.js'); ?>"></script>
<script src="<?= $module->assetUrl('javascript/panzoom.min.js'); ?>"></script>
<?= $usegraphviz ? "" : "<script src=\"" . $module->assetUrl('javascript/jspdf.umd.min.js') . "\"></script>"; ?>
<script type="text/javascript">
    const cartempty = <?= $cartempty ? "true" : "false" ?>;
    const CLIENT_ERRORS = ["<?= I18N::translate('Your browser does not support exporting images this large. Please reduce number of records, reduce DPI setting, or use SVG option.') ?>", "<?= I18N::translate('Unable to load setting ') ?>"];
    let autoUpdate = <?= $vars["auto_update"] ? 'true' : 'false' ?>;
    let debug_string = "";
    let TOMSELECT_URL = "";
    let settings_json = "";
    let download_file_name = "<?= e($settings['filename']); ?>";
    const TREE_NAME = "<?= e($tree->name()); ?>";
</script>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<form action="<?= $module->chartUrl($individual) ?>" method="post" class="wt-page-options sidebar d-print-none" id="gvexport" onchange="formChanged(autoUpdate)">

    <div class="pull-right btn-hover">
        <a href="#" class="hide-form btn btn-secondary">X</a>
    </div>

    <div class="sidebar__formfields col">

        <?= csrf_field() ?>

        <div class="d-flex">
            <h3><?= I18N::translate('People to be included') ?></h3>
        </div>

        <?php
        /* Check if another module (e.g. vesta classic) is adding the XREF to
           the name. If so, we want to enable the XREF option for individuals
           unless we already have a saved setting */
        $startName = $individual->fullName();
        $name = str_replace(" (" . $xref . ")", "", $startName);
        if ($startName != $name && isset($vars["first_run_xref_check"])) {
            $overridePID = true;
        } else {
            $overridePID = false;
        }

        $greypeople = false;
        // Check if there are INDI records in the clippings cart, to decide what options to allow
        if (!$cartempty) {
        if ($vars["use_cart"]) {
            $greypeople = true;
        }
        ?>

            <div class="row form-group">
                <?= MainPage::addLabel('', 'Clippings cart'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <?= I18N::translate('You have items in the clippings cart, which can be used for the diagram instead of the below options.') ?>
                    <div class="col-sm-8 wt-page-options-value">
                        <div class="row">
                            <div class="col-auto mx-3">
                                <input type="radio" onclick="toggleCart(true)" name="vars[use_cart]" id="usecart_yes" value="use_cart" <?= $vars["use_cart"] ? 'checked' : '' ?>>
                                <label for="usecart_yes"><?= I18N::translate('Use clippings cart') ?></label>
                            </div>
                            <div class="col-auto mx-3">
                                <input type="radio" onclick="toggleCart(false)" name="vars[use_cart]" id="usecart_no" value="ignorecart" <?= !$vars["use_cart"] ? 'checked' : '' ?>>
                                <label for="usecart_no"><?= I18N::translate('Ignore clippings cart') ?></label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>

        <div class="row form-group">
            <?= MainPage::addLabel('pid', 'Include anyone related to'); ?>
            <div class="col-sm-8 wt-page-options-value">
                <div id="indi_list">

                </div>
                <div id="clear_list"><a href="#" onclick="clearIndiList()"><?= I18N::translate('Clear all') ?></a></div>
                <div class="cart_toggle_hide" <?php if ($greypeople) { echo 'style="display: none"'; } ?>>
                    <?= view('components/select-individual', ['name' => 'pid', 'id' => 'pid', 'tree' => $tree, 'individual' => "", 'required'=>false]); ?>
                    <div class="red-text" id="indi-error"></div>
                </div>
            </div>
        </div>

        <div class="row form-group">
            <?= MainPage::addLabel('include_ancestors', 'Include ancestors'); ?>
            <div class="col-sm-8 wt-page-options-value">
                <div class="row">
                    <div class="col-auto mx-3">
                        <input class="cart_toggle" type="checkbox" name="vars[include_ancestors]" id="include_ancestors" value="ance" <?= $vars["include_ancestors"] ? 'checked' : '' ?>>
                    </div>
                    <div class="col-auto row">
                        <label for="ancestor_levels" class="col-sm-6"><?= I18N::translate('Max levels') ?>:</label>
                        <input onblur="defaultValueWhenBlank(this, 0)" type="text" class="cart_toggle form-control col-sm-6" size="10" name="vars[ancestor_levels]" id="ancestor_levels" value="<?= I18N::digits($vars["ancestor_levels"]); ?>">
                    </div>
                </div>
            </div>
        </div>

        <div class="row form-group">
            <?= MainPage::addLabel('', 'Include'); ?>
            <div class="col-sm-8 wt-page-options-value">
                <div class="row">
                    <div class="col-auto mx-3">
                        <input class="cart_toggle" type="checkbox" onclick="updateRelationOption('include_siblings')" name="vars[include_siblings]" id="include_siblings" value="sibl" <?= $vars["include_siblings"] ? 'checked' : '' ?>>
                        <label for="include_siblings"><?= I18N::translate('Siblings') ?></label>
                    </div>
                    <div class="col-auto mx-3">
                        <input class="cart_toggle" onclick="updateRelationOption('include_all_relatives')" type="checkbox" name="vars[include_all_relatives]" id="include_all_relatives" value="rels" <?= $vars["include_all_relatives"] ? 'checked' : '' ?>>
                        <label for="include_all_relatives"><?= I18N::translate('All relatives') ?></label>
                    </div>
                    <div class="col-auto mx-3">
                        <input class="cart_toggle" type="checkbox" onclick="updateRelationOption('include_spouses')" name="vars[include_spouses]" id="include_spouses" value="spou" <?= $vars["include_spouses"] ? 'checked' : '' ?>>
                        <label for="include_spouses"><?= I18N::translate('Partners') ?></label>
                    </div>
                    <div class="col-auto mx-3">
                        <input class="cart_toggle" type="checkbox" onclick="updateRelationOption('include_all')" name="vars[include_all]" id="include_all" value="any" <?= $vars["include_all"] ? 'checked' : '' ?> <?= !$cartempty ? "disabled" : ""; ?>>
                        <label for="include_all"><?= I18N::translate('Anyone') ?></label>
                    </div>
                </div>
            </div>
        </div>

        <div class="row form-group">
            <?= MainPage::addLabel('include_descendants', 'Include descendants'); ?>
            <div class="col-sm-8 wt-page-options-value">
                <div class="row">
                    <div class="col-auto mx-3">
                        <input class="cart_toggle" type="checkbox" name="vars[include_descendants]" id="include_descendants" value="desc" <?= $vars["include_descendants"] ? 'checked' : '' ?>>
                    </div>
                    <div class="col-auto row">
                        <label for="descendant_levels" class="col-sm-6"><?= I18N::translate('Max levels') ?>:</label>
                        <input onblur="defaultValueWhenBlank(this, 0)" type="text" class="cart_toggle form-control col-sm-6" size="10" name="vars[descendant_levels]" id="descendant_levels"
                               value="<?= I18N::digits($vars["descendant_levels"]); ?>">
                    </div>
                </div>
            </div>
        </div>
        <div id="people-advanced" <?= $vars["show_adv_people"] ? '' : 'style="display:none"'; ?>>
            <div class="row form-group">
                <?= MainPage::addLabel('xref_list', 'XREFs of included individuals'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="input-group mt-1">
                        <input type="text" class="form-control" name="vars[xref_list]" id="xref_list" value="<?= e($vars['xref_list']) ?>" onchange="refreshIndisFromXREFS(true)">
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-secondary" onclick="refreshIndisFromXREFS(false)">⟳</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <?= MainPage::addLabel('stop_xref_list', 'Stop processing on'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div id="stop_indi_list">

                    </div>
                    <div id="clear_stop_list"><a href="#" onclick="clearStopIndiList()"><?= I18N::translate('Clear all') ?></a></div>
                    <div class="cart_toggle_hide" <?php if ($greypeople) { echo 'style="display: none"'; } ?>>
                        <?php
                        echo view('components/select-individual', ['name' => 'vars[stop_pid]', 'id' => 'stop_pid', 'tree' => $tree, 'xref' => '']);
                        ?>
                    </div>
                    <div class="input-group mt-1">
                        <input type="text" class="cart_toggle form-control" name="vars[stop_xref_list]" id="stop_xref_list" value="<?= e($vars['stop_xref_list']); ?>" onchange="refreshIndisFromXREFS(true)">
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-secondary" onclick="refreshIndisFromXREFS(false)">⟳</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <?= MainPage::addLabel('mark_not_related', 'Non-relatives'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <input class="cart_toggle" onclick="setStateFastRelationCheck();" type="checkbox" name="vars[mark_not_related]" id="mark_not_related" value="mark_not_related" <?= $vars["mark_not_related"] ? 'checked' : '' ?>>
                    <label class="check-list" for="mark_not_related"><?= I18N::translate('Mark not blood-related people with different color') ?></label>
                    <br/>
                    <input class="cart_toggle" type="checkbox" name="vars[faster_relation_check]" id="faster_relation_check" value="faster_relation_check" <?= $vars["faster_relation_check"] ? 'checked' : '' ?>>
                    <label class="check-list" for="faster_relation_check"><?= I18N::translate('Ignore unseen links to speed up relative check') ?></label>
                </div>
            </div>
        </div>
        <a href="#" id="people-advanced-button" onclick="toggleAdvanced(this, 'people-advanced')"><div class="wt-page-options-label advanced-settings-btn"><?= ($vars["show_adv_people"] ? '↑ ' : '↓ ') . I18N::translate('Toggle advanced settings') . ($vars["show_adv_people"] ? ' ↑' : ' ↓'); ?></div></a>

        <h3><?= I18N::translate('Appearance') ?></h3>
        <div class="row form-group">
            <?= MainPage::addLabel('graph_dir', 'Graph direction'); ?>
            <div class="col-sm-8 wt-page-options-value">
                <?= view('components/select', ['name' => 'vars[graph_dir]', 'id' => 'graph_dir', 'selected' => e($vars['graph_dir']), 'options' => MainPage::updateTranslations($settings["directions"])]) ?>
            </div>
        </div>

        <div class="row form-group">
            <?= MainPage::addLabel('', 'Diagram type'); ?>
            <div class="col-sm-8 wt-page-options-value">
                <div class="row">
                    <div class="col-auto">
                        <input type="radio" onclick="togglePhotos(false)" name="vars[diagram_type]" id="diagtype_simple" value="simple" <?= $vars["diagram_type"] == "simple" ? 'checked' : '' ?>>
                        <label for="diagtype_simple"><?= I18N::translate('Simple') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="radio" onclick="togglePhotos(true)" name="vars[diagram_type]" id="diagtype_decorated" value="decorated" <?= $vars["diagram_type"] == "decorated" ? 'checked' : '' ?>>
                        <label for="diagtype_decorated"><?= I18N::translate('Decorated') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="radio" onclick="togglePhotos(true)" name="vars[diagram_type]" id="diagtype_combined" value="combined" <?= $vars["diagram_type"] == "combined" ? 'checked' : '' ?>>
                        <label for="diagtype_combined"><?= I18N::translate('Combined') ?></label>
                    </div>
                </div>
            </div>
        </div>

        <div id="appearance-advanced" <?= $vars["show_adv_appear"] ? '' : 'style="display:none"' ?>>

            <?php if ($tree->getPreference('SHOW_HIGHLIGHT_IMAGES') == '1') { ?>
                <div class="row form-group">
                    <?= MainPage::addLabel('show_photos', 'Add photos'); ?>
                    <div class="col-sm-8 wt-page-options-value">
                        <input type="checkbox" name="vars[show_photos]" id="show_photos" value="show_photos" <?= $vars["show_photos"] ? 'checked' : '' ?>>
                        <span class="text-muted">(<?= I18N::translate('Only Decorated or Combined') ?>)</span>
                    </div>
                </div>
            <?php } ?>

            <div class="row form-group">
                <?= MainPage::addLabel('add_links', 'Add URL to individuals and families'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="checkbox" name="vars[add_links]" id="add_links" value="add_links" <?= $vars["add_links"] ? 'checked' : '' ?>>
                    <span class="text-muted">(<?= $usegraphviz ? I18N::translate('browser, SVG, and PDF only') : I18N::translate('browser and SVG only'); ?>)</span>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('use_abbr_name', 'Abbreviated names'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <?= view('components/select', ['name' => 'vars[use_abbr_name]', 'id' => 'use_abbr_name', 'selected' => I18N::digits($vars['use_abbr_name']), 'options' => MainPage::updateTranslations($settings["use_abbr_names"])]) ?>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('use_abbr_place', 'Abbreviated place names'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <?= view('components/select', ['name' => 'vars[use_abbr_place]', 'id' => 'use_abbr_place', 'selected' => I18N::digits($vars['use_abbr_place']), 'options' => MainPage::updateTranslations($settings["use_abbr_places"])]) ?>
                </div>
            </div>
            
            <div class="row form-group">
                <?= MainPage::addLabel('show_xref_individuals', 'Show individual XREF'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="checkbox" name="vars[show_xref_individuals]" id="show_xref_individuals" value="show_xref_individuals" <?= $vars["show_xref_individuals"] || $overridePID ? 'checked' : '' ?>>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('show_birthdate', 'Show birth date'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="checkbox" name="vars[show_birthdate]" id="show_birthdate" value="show_birthdate" <?= $vars["show_birthdate"] ? 'checked' : '' ?>>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[birthdate_year_only]" id="bd_type_y" value="true" <?= $vars["birthdate_year_only"] ? 'checked' : '' ?>>
                            <label for="bd_type_y"><?= I18N::translate('Year') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[birthdate_year_only]" id="bd_type_gedcom" value="false" <?= !$vars["birthdate_year_only"] ? 'checked' : '' ?>>
                            <label for="bd_type_gedcom"><?= I18N::translate('Full date') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('show_birthplace', 'Show birth place'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="checkbox" name="vars[show_birthplace]" id="show_birthplace" value="show_birthplace" <?= $vars["show_birthplace"] ? 'checked' : '' ?>>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('show_death_date', 'Show death date'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="checkbox" name="vars[show_death_date]" id="show_death_date" value="show_death_date" <?= $vars["show_death_date"] ? 'checked' : '' ?>>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[death_date_year_only]" id="dd_type_y" value="true" <?= $vars["death_date_year_only"] ? 'checked' : '' ?>>
                            <label for="dd_type_y"><?= I18N::translate('Year') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[death_date_year_only]" id="dd_type_gedcom" value="false" <?= !$vars["death_date_year_only"] ? 'checked' : '' ?>>
                            <label for="dd_type_gedcom"><?= I18N::translate('Full date') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('show_death_place', 'Show death place'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="checkbox" name="vars[show_death_place]" id="show_death_place" value="show_death_place" <?= $vars["show_death_place"] ? 'checked' : '' ?>>
                </div>
            </div>


            <div class="row form-group">
                <?= MainPage::addLabel('show_xref_families', 'Show family XREF'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="checkbox" name="vars[show_xref_families]" id="show_xref_families" value="show_xref_families" <?= $vars["show_xref_families"] ? 'checked' : '' ?>>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('show_marriage_date', 'Show marriage date'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="checkbox" name="vars[show_marriage_date]" id="show_marriage_date" value="show_marriage_date" <?= $vars["show_marriage_date"] ? 'checked' : '' ?>>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[marr_date_year_only]" id="md_type_y" value="true" <?= $vars["marr_date_year_only"] ? 'checked' : '' ?>>
                            <label for="md_type_y"><?= I18N::translate('Year') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[marr_date_year_only]" id="md_type_gedcom" value="false" <?= !$vars["marr_date_year_only"] ? 'checked' : '' ?>>
                            <label for="md_type_gedcom"><?= I18N::translate('Full date') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('show_marriage_place', 'Show marriage place'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="checkbox" name="vars[show_marriage_place]" id="show_marriage_place" value="show_marriage_place" <?= $vars["show_marriage_place"] ? 'checked' : '' ?>>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('dpi', 'DPI'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto">
                            <input type="text" onblur="defaultValueWhenBlank(this, 72)" class="form-control" size="10" name="vars[dpi]" id="dpi"
                                   value="<?= I18N::digits($vars["dpi"]); ?>">
                        </div>
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <?= MainPage::addLabel('', 'Space'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <label for="ranksep"><?= I18N::translate('Between generations') ?>:</label>
                        <div class="col-auto">
                            <input type="text" onclick="togglePercent(this, false)" onblur="togglePercent(this, true)" class="form-control col-sm-6" size="10" name="vars[ranksep]" id="ranksep"
                                   value="<?= e($vars["ranksep"]) ?>">
                        </div>
                        <label for="nodesep"><?= I18N::translate('Between individuals on the same level') ?>:</label>
                        <div class="col-auto">
                            <input type="text" onclick="togglePercent(this, false)" onblur="togglePercent(this, true)" class="form-control col-sm-6" size="10" name="vars[nodesep]" id="nodesep"
                                   value="<?= e($vars["nodesep"]) ?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <?= MainPage::addLabel('', 'Font'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <label for="typeface"><?= I18N::translate('Typeface') ?>:</label>
                        <div class="col-auto">
                            <?= view('components/select', ['name' => 'vars[typeface]', 'id' => 'typeface', 'selected' => I18N::digits($vars['typeface']), 'options' => MainPage::updateTranslations($settings["typefaces"])]) ?>
                        </div>
                        <label for="font_size_name"><?= I18N::translate('Font size for names') ?>:</label>
                        <div class="col-auto">
                            <input type="text" class="form-control col-sm-6" size="10" name="vars[font_size_name]" id="font_size_name" value="<?= I18N::digits($vars["font_size_name"]); ?>">
                        </div>
                        <label for="font_size"><?= I18N::translate('Font size for details') ?>:</label>
                        <div class="col-auto">
                            <input type="text" class="form-control col-sm-6" size="10" name="vars[font_size]" id="font_size" value="<?= I18N::digits($vars["font_size"]); ?>">
                        </div>
                        <div>
                            <input type="color" class="picker" name="vars[font_colour_name]" id="font_colour_name" value="<?= e($vars["font_colour_name"]); ?>" /><label for="font_colour_name" class="picker-label"><?= I18N::translate('Font color for names') ?></label>
                        </div>

                        <div>
                            <input type="color" class="picker" name="vars[font_colour_details]" id="font_colour_details" value="<?= e($vars["font_colour_details"]); ?>" /><label for="font_colour_details" class="picker-label"><?= I18N::translate('Font color for details') ?></label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <?= MainPage::addLabel('', 'Relationship arrows'); ?>
                <div class="col-sm-8 wt-page-options-value">
                        <div class="col-auto">
                            <input type="color" class="picker" name="vars[arrows_default]" id="arrows_default" value="<?= e($vars["arrows_default"]); ?>" /><label for="arrows_default" class="picker-label"><?= I18N::translate('Arrow color') ?></label>
                        </div>
                        <input type="checkbox" name="vars[colour_arrow_related]" onclick="showHide(document.getElementById('arrow_group'),this.checked)" id="colour_arrow_related" value="colour_arrow_related" <?= $vars["colour_arrow_related"] ? 'checked' : '' ?>><label for="colour_arrow_related" class="check-list"><?= I18N::translate('Show blood relationship in different color') ?></label>

                        <div id="arrow_group" class="color_subgroup col-auto wt-page-options-value" <?= !$vars["colour_arrow_related"] ? 'style="display:none;"' : '' ?>>
                            <div class="sub-group">
                                <input type="color" class="picker" name="vars[arrows_related]" id="arrows_related" value="<?= e($vars["arrows_related"]); ?>" /><label for="arrows_related" class="picker-label"><?= I18N::translate('Related by birth') ?></label>
                                <input type="color" class="picker" name="vars[arrows_not_related]" id="arrows_not_related" value="<?= e($vars["arrows_not_related"]); ?>" /><label for="arrows_not_related" class="picker-label"><?= I18N::translate('Related other than by birth') ?></label>
                            </div>
                        </div>
                </div>
            </div>
            <div class="row form-group">
                <?= MainPage::addLabel('', 'Tile colors'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[male_col]" id="male_col" value="<?= e($vars["male_col"]); ?>" /><label for="male_col" class="picker-label"><?= I18N::translate('Male individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[female_col]" id="female_col" value="<?= e($vars["female_col"]); ?>" /><label for="female_col" class="picker-label"><?= I18N::translate('Female individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[other_gender_col]" id="other_gender_col" value="<?= e($vars["other_gender_col"]); ?>" /><label for="other_gender_col" class="picker-label"><?= I18N::translate('Other gender individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[unknown_gender_col]" id="unknown_gender_col" value="<?= e($vars["unknown_gender_col"]); ?>" /><label for="unknown_gender_col" class="picker-label"><?= I18N::translate('Unknown gender individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[male_unrelated_col]" id="male_unrelated_col" value="<?= e($vars["male_unrelated_col"]); ?>" /><label for="male_unrelated_col" class="picker-label"><?= I18N::translate('Not blood-related male individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[female_unrelated_col]" id="female_unrelated_col" value="<?= e($vars["female_unrelated_col"]); ?>" /><label for="female_unrelated_col" class="picker-label"><?= I18N::translate('Not blood-related female individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[oth_gender_unrel_col]" id="oth_gender_unrel_col" value="<?= e($vars["oth_gender_unrel_col"]); ?>" /><label for="oth_gender_unrel_col" class="picker-label"><?= I18N::translate('Not blood-related other gender individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[unkn_gender_unrel_col]" id="unkn_gender_unrel_col" value="<?= e($vars["unkn_gender_unrel_col"]); ?>" /><label for="unkn_gender_unrel_col" class="picker-label"><?= I18N::translate('Not blood-related unknown gender individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[indi_background_col]" id="indi_background_col" value="<?= e($vars["indi_background_col"]); ?>" /><label for="indi_background_col" class="picker-label"><?= I18N::translate('Individual background color') ?></label>
                    </div>
                    <input type="checkbox" name="vars[highlight_start_indis]" onclick="showHide(document.getElementById('startcol_option'),this.checked)" id="highlight_start_indis" value="true" <?= $vars["highlight_start_indis"] ? 'checked' : '' ?>><label for="highlight_start_indis" class="check-list"><?= I18N::translate('Show starting persons in different color') ?></label>
                    <div class="color_subgroup col-auto wt-page-options-value" id="startcol_option"  <?= $vars["highlight_start_indis"] != "true" ? 'style="display:none;"' : '' ?>>
                        <input type="color" class="picker" name="vars[highlight_col]" id="highlight_col" value="<?= e($vars["highlight_col"]); ?>" /><label for="highlight_col" class="picker-label"><?= I18N::translate('Starting persons background color') ?></label>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <?= MainPage::addLabel('', 'Other colours'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[family_col]" id="family_col" value="<?= e($vars["family_col"]); ?>" /><label for="family_col" class="picker-label"><?= I18N::translate('Family background') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[border_col]" id="border_col" value="<?= e($vars["border_col"]); ?>" /><label for="border_col" class="picker-label"><?= I18N::translate('Outline colour') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[background_col]" id="background_col" value="<?= e($vars["background_col"]); ?>" /><label for="background_col" class="picker-label"><?= I18N::translate('Diagram background color') ?></label>
                    </div>
                </div>
            </div>
        </div>
        <a href="#" id="appearance-advanced-button" onclick="toggleAdvanced(this, 'appearance-advanced')"><div class="wt-page-options-label advanced-settings-btn"><?= ($vars["show_adv_appear"] ? '↑ ' : '↓ ') . I18N::translate('Toggle advanced settings') . ($vars["show_adv_appear"] ? ' ↑' : ' ↓'); ?></div></a>
        <h3><?= I18N::translate('File settings') ?></h3>
        <div class="row form-group">
            <?= MainPage::addLabel('output_type', 'Output file type'); ?>
            <div class="col-sm-8 wt-page-options-value">
                <?= view('components/select', ['name' => 'vars[output_type]', 'id' => 'output_type', 'selected' => e($vars['output_type']), 'options' => $otypes]) ?>
                <small id="emailHelp" class="form-text text-muted"><?= $usegraphviz ? "" : I18N::translate("Options limited as Graphviz not installed on server") ?></small>
            </div>
        </div>
        <div id="files-advanced" <?= $vars["show_adv_files"] ? '' : 'style="display:none"'; ?>>
            <div class="row form-group">
                <?= MainPage::addLabel('auto_update', 'Browser render'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <label for="auto_update"><?= I18N::translate('Auto-update') ?></label>
                    <input type="checkbox" onclick="toggleUpdateButton()" name="vars[auto_update]" id="auto_update" value="auto_update" <?= $vars["auto_update"] ? 'checked' : '' ?>>
                </div>
                <?= MainPage::addLabel('save_settings', 'Save settings'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="input-group mt-1">
                        <input type="text" class="form-control" name="vars[save_settings]" id="save_settings" placeholder="Settings name">
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-secondary" onclick=""><?= I18N::translate('Save') ?></button>
                        </div>
                    </div>
                </div>
                <?= MainPage::addLabel('', 'Settings file'); ?>
                <div class="col-sm-8 wt-page-options-value">
                    <label for="save_settings"><?= I18N::translate('Save settings to file') ?></label><br>
                    <button class="btn btn-outline-secondary" type="button" name="save_settings" id="save_settings" onclick="downloadSettingsFile(true)"><?= I18N::translate('Download') ?></button><br>
                    <label for="save_settings"><?= I18N::translate('Load settings from file') ?></label><br>
                    <input type="file" onchange="uploadSettingsFile(this)">
                </div>
            </div>
        </div>
        <a href="#" id="files-advanced-button" onclick="toggleAdvanced(this, 'files-advanced')"><div class="wt-page-options-label advanced-settings-btn"><?= ($vars["show_adv_files"] ? '↑ ' : '↓ ') . I18N::translate('Toggle advanced settings') . ($vars["show_adv_files"] ? ' ↑' : ' ↓'); ?></div></a>
        <?php if ($vars["show_debug_panel"]) { ?>
        <h3><?= I18N::translate('Debug') ?></h3>
        <div class="row form-group">
            <?= MainPage::addLabel('enable_debug_mode', 'Debug mode', FALSE); ?>
            <div class="col-sm-8 wt-page-options-value">
                <label for="enable_debug_mode"><?= I18N::translate('Enable debug mode') ?></label>
                <input type="checkbox" name="vars[enable_debug_mode]" id="enable_debug_mode" value="enable_debug_mode" <?= $vars["enable_debug_mode"] ? 'checked' : '' ?>><br>
                <button class="btn btn-outline-secondary" type="button" name="debug_view" onclick="return showHelp('enable_debug_mode');"><?= I18N::translate('View debug log') ?></button>
            </div>
            <?= MainPage::addLabel('enable_debug_mode', 'Settings JSON', FALSE); ?>
            <div class="col-sm-8 wt-page-options-value">
                <button class="btn btn-outline-secondary" type="button" name="debug_view" onclick="return showHelp('debug_settings');"><?= I18N::translate('View settings JSON') ?></button>
            </div>
            <?= MainPage::addLabel('enable_graphviz', 'Graphviz', FALSE); ?>
            <div class="col-sm-8 wt-page-options-value">
                <label for="enable_graphviz"><?= I18N::translate('Use Graphviz on server') ?></label>
                <input type="checkbox" name="vars[enable_graphviz]" id="enable_graphviz" value="enable_graphviz" onclick="setGraphvizAvailable(this.value==='enable_graphviz');" <?= $vars["enable_graphviz"] ? 'checked' : '' ?> <?= (new Settings())->getDefaultSettings()['graphviz_bin'] == "" ? "disabled" : ""; ?>><br></div>
        </div>
        <?php } ?>
    </div>

    <div class="sidebar__buttons">
        <button type="submit" class="btn btn-primary update-browser-rendering" id="update-browser" <?php if ($vars["auto_update"]) { echo 'style="display: none"'; } ?>><?= I18N::translate('Update') ?></button>
        <button type="submit" class="btn btn-secondary main-action" name="download"><?= I18N::translate('Download') ?></button>
        <a href="<?= $module->chartUrl($individual, ['reset' => '1']) ?>" class="btn btn-outline-secondary"><?= I18N::translate('Reset') ?></a>
        <button class="btn btn-outline-secondary" name="help" onclick="return showHelp('Help')"><?= I18N::translate('Help') ?></button>
    </div>

    <input type="hidden" id="browser" name="browser" value="false">
    <input type="hidden" id="people-advanced-hidden" name="vars[show_adv_people]" value="<?= $vars["show_adv_people"] ? 'show' : '' ?>">
    <input type="hidden" id="appearance-advanced-hidden" name="vars[show_adv_appear]" value="<?= $vars["show_adv_appear"] ? 'show' : '' ?>">
    <input type="hidden" id="files-advanced-hidden" name="vars[show_adv_files]" value="<?= $vars["show_adv_files"] ? 'show' : '' ?>">
    <div id="toast-container"></div>
</form>

<div class="sidebar__toggler" hidden>
    <a href="#" class="btn btn-outline-secondary"><?= I18N::translate('Show options') ?></a>
</div>

<div id="render-container">
    <div id="rendering" hidden style="background-color: <?= $vars["background_col"] ?>;"></div>
    <a href="#" title="<?= I18N::translate('Fullscreen') ?>" onclick="toggleFullscreen()" class="fullscreen" id="fullscreenButton">⛶</a>
    <a href="#" title="<?= I18N::translate('Exit fullscreen') ?>" onclick="toggleFullscreen()" class="fullscreen" id="fullscreenClose" style="display: none;">✖</a>
</div>

<script type="text/javascript">
    let graphvizAvailable = <?= $usegraphviz ? "true" : "false" ?>;
    let panzoomInst = null;
    const workerURL = '<?= $module->assetUrl('javascript/full.renderer.js'); ?>';
    let viz = new Viz({
        workerURL: workerURL
    });

    const form = document.getElementById('gvexport');
    const rendering = document.getElementById('rendering');


    // Trigger action when "Update" button clicked
    document.querySelector('.update-browser-rendering').addEventListener('click', function(e) {
        if (checkIndiBlank() === false) {
            updateRender();
            removeError("indi-error");
        } else {
            addError("indi-error","<?= I18N::translate("Individual required") ?>");
        }
        e.preventDefault();
    });

    // If "Download" button clicked
    document.querySelector('.main-action').addEventListener('click', function(e) {
        // first check that individual has been selected
        if (checkIndiBlank() === false) {
            removeError("indi-error");
        } else {
            addError("indi-error","<?= I18N::translate("Individual required") ?>");
            e.preventDefault();
        }
        // Also check if Graphviz installed. If so then let it handle it,
        // but if not, trigger client side actions
        if (!graphvizAvailable) {
            const output = document.getElementById('output_type').value;
            switch(output) {
                case "png":
                    downloadSVGAsPNG();
                    break;
                case "svg":
                    downloadSVGAsText();
                    break;
                case "jpg":
                    downloadSVGAsJPEG();
                    break;
                case "pdf":
                    downloadSVGAsPDF();
                    break;
                default:
            }
            if (output !== "dot") {
                e.preventDefault();
            }
        }
    });

    function updateRender() {
        // Set browser value to true so we can return other info with DOT file
        // that can't be included with downloaded file
        document.getElementById("browser").value = "true";

        // Update render element background to match diagram background
        document.getElementById("rendering").style.background = document.getElementById("background_col").value;

        // Enable disabled fields so they are included in serialised data - this means the values are remembered
        const el = document.getElementsByClassName("cart_toggle");
        for (let i = 0; i < el.length; i++) {
            el.item(i).disabled = false;
        }
        // Get the form data
        const data = jQuery(form).serialize();
        // Disable our fields again by indicating cart is enabled (only if items in cart)
        if (!cartempty && document.getElementById("usecart_yes").checked) {
            toggleCart(true);
        }
        setStateFastRelationCheck();
        refreshIndisFromXREFS(false);
        document.getElementById("browser").value = "false";
        let lastDotStr, indiNum, famNum, messages;

        rendering.innerHTML = '<div class="d-flex justify-content-center h-100"><div class="spinner-border align-self-center" role="status"><span class="sr-only">Loading...</span></div></div>';
        rendering.hidden = false;

        const MARGIN = 50;
        const h = window.innerHeight - document.querySelector('.wt-header-wrapper').getBoundingClientRect().height - document.querySelector('.wt-footers').getBoundingClientRect().height;
        const w = window.innerWidth - MARGIN*2;
        const wtMainContainer = document.getElementsByClassName('wt-main-container').item(0);
        const wtTitle = document.getElementsByClassName("wt-page-title").item(0);
        // Set size of render element to fit browser
        document.getElementById('render-container').style.height = h + "px";
        document.getElementById('render-container').style.width = w + "px";
        document.getElementById('render-container').style.left = MARGIN + "px";
        // Set size of container element so webtrees footer is in the right place
        const totalHeight = MARGIN + wtTitle.getBoundingClientRect().height + getComputedProperty(wtTitle, 'margin-bottom') + h + getComputedProperty(wtMainContainer, 'padding-top');
        wtMainContainer.style.height = totalHeight + "px";

        window.fetch(form.getAttribute('action'), {
            method: form.getAttribute('method'),
            credentials: 'same-origin', // include, *same-origin, omit
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body: data
        }).then(function (response) {
            if (!response.ok) {
                return response.text().then(function (errorText) {
                    return Promise.reject(errorText)
                });
            }
            return response.text();
        }).then(function (response) {
            let jsonResponse;
            // If login expires, we will get error page instead of JSON.
            // Reload if loading JSON fails
            try {
                jsonResponse = JSON.parse(response);
            } catch(e) {
                showToast(ERROR_CHAR + "<?= I18N::translate('Login expired. Reloading page...'); ?>");
                showToast(ERROR_CHAR + e);
                setTimeout(function(){location.reload();}, 3000);
                return false;
            }
            lastDotStr = jsonResponse.dot;
            if (lastDotStr.indexOf("digraph WT_Graph {") !== -1) {
                messages = jsonResponse.messages;
                debug_string = jsonResponse.enable_debug_mode;
                settings_json = jsonResponse.settings;
            }

            const images = [...lastDotStr.matchAll(/<IMG[^>]+SRC="([^"]*)/gmi)].map(function (matches) {
                return {
                    path: matches[1],
                    width: '150px',
                    height: '150px'
                };
            });
            return viz.renderSVGElement(lastDotStr, {
                images: images
            });
        }).then(function (element) {
            // Now we have to clean up the generated SVG.

            // remove title tags, so we don't get weird data on hover,
            // instead this defaults to the XREF of the record
            const a = element.getElementsByTagName("a");
            for (let i = 0; i < a.length; i++) {
                a[i].removeAttribute("xlink:title");
            }
            //half of bug fix for photos not showing in browser - we change & to %26 in functions_dot.php
            element.innerHTML = element.innerHTML.replaceAll("%26", "&amp;");
            // Don't show anything when hovering on blank space
            element.innerHTML = element.innerHTML.replaceAll("<title>WT_Graph</title>", "");
            // Set SVG viewBox to height/width so image is not cut off
            element.setAttribute("viewBox", "0 0 "+element.getAttribute("width").replace("pt","")+" "+element.getAttribute("height").replace("pt",""));
            // Clear current rendering then append new element to the page
            rendering.innerHTML = "";
            rendering.appendChild(element);
            const fullZoom = Math.min(4, rendering.getBoundingClientRect().width / element.getBBox().width);
            panzoomInst = panzoom(element, {
                maxZoom: 4,
                minZoom: fullZoom / 4,
                initialZoom: fullZoom,
                onTouch: function() {
                    // Fix links not working on mobile
                    return false; // tells the library to not preventDefault.
                }
            });
            if (messages !== "") {
                for (let i = 0; i < messages.length; i++) {
                    showToast(messages[i]);
                }
            }
            // Scroll render to last starting individual
            let indiList = document.getElementById('xref_list').value.split(",");
            for (let i = indiList.length-1; i>=0; i--) {
                if (indiList[i].trim() !== "") {
                    scrollToRecord(indiList[i].trim());
                    break;
                }
            }

            handleTileClick();

            return element;
        }).catch(function (error) {
            if (error.message.includes("TOTAL_MEMORY")) {
                if (graphvizAvailable) {
                    showToast(ERROR_CHAR + "<?= I18N::translate('Memory limit reached. Please reduce number of records or use download option.'); ?>");
                } else {
                        showToast(ERROR_CHAR + "<?= I18N::translate('Memory limit reached. Please reduce number of records or install Graphviz on server and use download option.'); ?>");
                }
                rendering.innerHTML = "";
            } else {
                rendering.innerHTML = '<div class="alert alert-danger" role="alert"><?= I18N::translate('Error running GVExport in browser mode') ?>:<br>' + error + '</div>';
                if (lastDotStr) {
                    rendering.innerHTML = rendering.innerHTML + '<h4>DOT contents</h4><pre id="dot-text"></pre>';
                    document.getElementById('dot-text').appendChild(document.createTextNode(lastDotStr));
                }
            }


            // Create a new Viz instance (@see Caveats page for more info)
            viz = new Viz({
                workerURL: workerURL
            });
        });
        return false;
    }

    // Add an error message to the page
    // id - the id of the element that holds the message
    // message - the text to show in the error message
    function addError(id, message) {
        let er = document.getElementById(id);
        er.innerText=message;
        let el = document.getElementsByClassName("sidebar__formfields");
        let form = document.getElementsByTagName("FORM");
        let pos = getPos(er,form.item(1));
        el.item(0).scrollTo(0,pos["y"]-70);
    }

    // Removes the error text in the provided element
    function removeError(id) {
        let er = document.getElementById(id);
        er.innerText="";
    }

    <?php echo (new Help())->addHelpMessageJavaScript(); ?>
</script>

