<?php

namespace vendor\WebtreesModules\gvexport;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;

/**
 * @var string      $gvexport_css           used in javascript code as a link to the css file
 * @var string      $gvexport_js            used in javascript code as a link to the external script file
 * @var string      $title                  title of this page
 * @var array       $vars                   array of saved settings
 * @var array       $otypes                 output file type options
 * @var ?           $module                 this module
 */
$settingsObj = new Settings($module);
$settings = $settingsObj->getSettings();
?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>
<p><?= I18N::translate('Values here are used as default values for new users of GVExport, and are used when users choose to reset the settings.'); ?></p>
<script type="text/javascript">
    // stylesheet
    var newSheet = document.createElement("link");
    newSheet.setAttribute("rel","stylesheet");
    newSheet.setAttribute("type","text/css");
    newSheet.setAttribute("href","<?= $gvexport_css ?>");
    document.head.appendChild(newSheet);

    // Javascript functions
    var newScript = document.createElement("script");
    newScript.setAttribute("type","text/javascript");
    newScript.setAttribute("src","<?= $gvexport_js ?>");
    document.head.appendChild(newScript);
</script>
<div class="mb-5">
    <form method="post">
        <?= csrf_field() ?>
        <h2><?= I18N::translate('Default values for GVExport'); ?></h2>

        <div>
            <div>
                <h3><?= I18N::translate('People to be included') ?></h3>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="indiance"><?= I18N::translate('Use clippings cart') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[usecart]" id="usecart_yes" value="usecart" <?= $vars["usecart"] == "usecart" ? 'checked' : '' ?>>
                            <label for="usecart_yes"><?= I18N::translate('Use clippings cart') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[usecart]" id="usecart_no" value="ignorecart" <?= $vars["usecart"] == "ignorecart" ? 'checked' : '' ?>>
                            <label for="usecart_no"><?= I18N::translate('Ignore clippings cart') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="indiance"><?= I18N::translate('Include ancestors') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[indiance]" value="no">
                            <input class="cart_toggle" type="checkbox" name="vars[indiance]" id="indiance" value="ance" <?= $vars["indiance"] == "ance" ? 'checked' : '' ?>>
                        </div>
                        <div class="col-auto row">
                            <label for="ance_level" class="col-sm-6"><?= I18N::translate('Max levels') ?>:</label>
                            <input class="cart_toggle" onblur="defaultValueWhenBlank(this, 0)" type="text" class="form-control col-sm-6" size="10" name="vars[ance_level]" id="ance_level" value="<?= $vars["ance_level"] ?>">
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label"><?= I18N::translate('Include') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[indisibl]" value="no">
                            <input class="cart_toggle" type="checkbox" onclick="updateRelationOption('indisibl')" name="vars[indisibl]" id="indisibl" value="sibl" <?= $vars["indisibl"] == "sibl" ? 'checked' : '' ?>>
                            <label for="indisibl"><?= I18N::translate('Siblings') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[indicous]" value="no">
                            <input class="cart_toggle" onclick="updateRelationOption('indicous')" type="checkbox" name="vars[indicous]" id="indicous" value="cous" <?= $vars["indicous"] == "cous" ? 'checked' : '' ?>>
                            <label for="indicous"><?= I18N::translate('All relatives') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[indispou]" value="no">
                            <input class="cart_toggle" type="checkbox" onclick="updateRelationOption('indispou')" name="vars[indispou]" id="indispou" value="spou" <?= $vars["indispou"] == "spou" ? 'checked' : '' ?>>
                            <label for="indispou"><?= I18N::translate('Partners') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[indiany]" value="no">
                            <input class="cart_toggle" type="checkbox" onclick="updateRelationOption('indiany')" name="vars[indiany]" id="indiany" value="any" <?= $vars["indiany"] == "any" ? 'checked' : '' ?> >
                            <label for="indiany"><?= I18N::translate('Anyone') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="indidesc"><?= I18N::translate('Include descendants') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[indidesc]" value="no">
                            <input class="cart_toggle" type="checkbox" name="vars[indidesc]" id="indidesc" value="desc" <?= $vars["indidesc"] == "desc" ? 'checked' : '' ?>>
                        </div>
                        <div class="col-auto row">
                            <label for="desc_level" class="col-sm-6"><?= I18N::translate('Max levels') ?>:</label>
                            <input class="cart_toggle"  onblur="defaultValueWhenBlank(this, 0)" type="text" class="form-control col-sm-6" size="10" name="vars[desc_level]" id="desc_level" value="<?= $vars["desc_level"] ?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label" for="marknr"><?= I18N::translate('Non-relatives') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="hidden" name="vars[marknr]" value="no">
                    <input class="cart_toggle" type="checkbox" name="vars[marknr]" id="marknr" value="marknr" <?= $vars["marknr"] == "marknr" ? 'checked' : '' ?>>
                    <label class="check-list" for="marknr"><?= I18N::translate('Mark not blood-related people with different color') ?></label>
                    <br/>
                    <input type="hidden" name="vars[fastnr]" value="no">
                    <input class="cart_toggle" type="checkbox" name="vars[fastnr]" id="fastnr" value="fastnr" <?= $vars["fastnr"] == "fastnr" ? 'checked' : '' ?>>
                    <label class="check-list" for="fastnr"><?= I18N::translate('Ignore unseen links to speed up relative check') ?></label>
                </div>
            </div>

            <h3><?= /* I18N: Appearance heading */ I18N::translate('Appearance') ?></h3>

            <div class="row">
                <label class=" col-sm-4 col-form-label" for="grdir"><?= I18N::translate('Graph direction') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <?= view('components/select', ['name' => 'vars[grdir]', 'id' => 'grdir', 'selected' => $vars['grdir'], 'options' => MainPage::updateTranslations($settings["directions"])]) ?>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label"><?= I18N::translate('Diagram type') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto">
                            <input type="radio" name="vars[diagtype]" id="diagtype_simple" value="simple" <?= $vars["diagtype"] == "simple" ? 'checked' : '' ?>>
                            <label for="diagtype_simple"><?= I18N::translate('Simple') ?></label>
                        </div>
                        <div class="col-auto">
                            <input type="radio" name="vars[diagtype]" id="diagtype_decorated" value="decorated" <?= $vars["diagtype"] == "decorated" ? 'checked' : '' ?>>
                            <label for="diagtype_decorated"><?= I18N::translate('Decorated') ?></label>
                        </div>
                        <div class="col-auto">
                            <input type="radio" name="vars[diagtype]" id="diagtype_combined" value="combined" <?= $vars["diagtype"] == "combined" ? 'checked' : '' ?>>
                            <label for="diagtype_combined"><?= I18N::translate('Combined') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="with_photos"><?= I18N::translate('Add photos') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="hidden" name="vars[with_photos]" value="no">
                    <input type="checkbox" name="vars[with_photos]" id="with_photos" value="with_photos" <?= $vars["with_photos"] == "with_photos" ? 'checked' : '' ?>>
                    <span class="text-muted">(<?= I18N::translate('Only Decorated or Combined') ?>)</span>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_url"><?= I18N::translate('Add URL to individuals and families') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="hidden" name="vars[show_url]" value="no">
                    <input type="checkbox" name="vars[show_url]" id="show_url" value="show_url" <?= $vars["show_url"] == "show_url" ? 'checked' : '' ?>>
                    <span class="text-muted">(<?= I18N::translate('SVG only') ?>)</span>
                </div>
            </div>

            <div class="row">
                <label class=" col-sm-4 col-form-label" for="use_abbr_name"><?= I18N::translate('Abbreviated names') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <?= view('components/select', ['name' => 'vars[use_abbr_name]', 'selected' => $vars['use_abbr_name'], 'options' => MainPage::updateTranslations($settings["use_abbr_names"])]) ?>
                </div>
            </div>

            <div class="row">
                <label class=" col-sm-4 col-form-label" for="use_abbr_place"><?= I18N::translate('Abbreviated place names') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <?= view('components/select', ['name' => 'vars[use_abbr_place]', 'selected' => $vars['use_abbr_place'], 'options' => MainPage::updateTranslations($settings["use_abbr_places"])]) ?>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_pid"><?= I18N::translate('Show individual XREF') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="hidden" name="vars[show_pid]" value="no">
                    <input type="checkbox" name="vars[show_pid]" id="show_pid" value="show_pid" <?= $vars["show_pid"] == "show_pid" ? 'checked' : '' ?>>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_by"><?= I18N::translate('Show birth date') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[show_by]" value="no">
                            <input type="checkbox" name="vars[show_by]" id="show_by" value="show_by" <?= $vars["show_by"] == "show_by" ? 'checked' : '' ?>>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[bd_type]" id="bd_type_y" value="y" <?= $vars["bd_type"] == "y" ? 'checked' : '' ?>>
                            <label for="bd_type_y"><?= I18N::translate('Year') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[bd_type]" id="bd_type_gedcom" value="gedcom" <?= $vars["bd_type"] == "gedcom" ? 'checked' : '' ?>>
                            <label for="bd_type_gedcom"><?= I18N::translate('Full date') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_bp"><?= I18N::translate('Show birth place') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="hidden" name="vars[show_bp]" value="no">
                    <input type="checkbox" name="vars[show_bp]" id="show_bp" value="show_bp" <?= $vars["show_bp"] == "show_bp" ? 'checked' : '' ?>>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_dy"><?= I18N::translate('Show death date') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[show_dy]" value="no">
                            <input type="checkbox" name="vars[show_dy]" id="show_dy" value="show_dy" <?= $vars["show_dy"] == "show_dy" ? 'checked' : '' ?>>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[dd_type]" id="dd_type_y" value="y" <?= $vars["dd_type"] == "y" ? 'checked' : '' ?>>
                            <label for="dd_type_y"><?= I18N::translate('Year') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[dd_type]" id="dd_type_gedcom" value="gedcom" <?= $vars["dd_type"] == "gedcom" ? 'checked' : '' ?>>
                            <label for="dd_type_gedcom"><?= I18N::translate('Full date') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_dp"><?= I18N::translate('Show death place') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="hidden" name="vars[show_dp]" value="no">
                    <input type="checkbox" name="vars[show_dp]" id="show_dp" value="show_dp" <?= $vars["show_dp"] == "show_dp" ? 'checked' : '' ?>>
                </div>
            </div>


            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_fid"><?= I18N::translate('Show family XREF') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="hidden" name="vars[show_fid]" value="no">
                    <input type="checkbox" name="vars[show_fid]" id="show_fid" value="show_fid" <?= $vars["show_fid"] == "show_fid" ? 'checked' : '' ?>>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_my"><?= I18N::translate('Show marriage date') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto mx-3">
                            <input type="hidden" name="vars[show_my]" value="no">
                            <input type="checkbox" name="vars[show_my]" id="show_my" value="show_my" <?= $vars["show_my"] == "show_my" ? 'checked' : '' ?>>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[md_type]" id="md_type_y" value="y" <?= $vars["md_type"] == "y" ? 'checked' : '' ?>>
                            <label for="md_type_y"><?= I18N::translate('Year') ?></label>
                        </div>
                        <div class="col-auto mx-3">
                            <input type="radio" name="vars[md_type]" id="md_type_gedcom" value="gedcom" <?= $vars["md_type"] == "gedcom" ? 'checked' : '' ?>>
                            <label for="md_type_gedcom"><?= I18N::translate('Full date') ?></label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <label class="col-sm-4 col-form-label" for="show_mp"><?= I18N::translate('Show marriage place') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <input type="hidden" name="vars[show_mp]" value="no">
                    <input type="checkbox" name="vars[show_mp]" id="show_mp" value="show_mp" <?= $vars["show_mp"] == "show_mp" ? 'checked' : '' ?>>
                </div>
            </div>

            <div class="row">
                <label class=" col-sm-4 col-form-label" for="dpi"><?= I18N::translate('DPI') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <div class="col-auto">
                            <input type="text" onblur="defaultValueWhenBlank(this, 72)" class="form-control" size="10" name="vars[dpi]" id="dpi" value="<?= $vars["dpi"] ?>">
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <label class=" col-sm-4 col-form-label" for="dpi"><?= I18N::translate('Space') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <label for="ranksep"><?= I18N::translate('Between generations') ?>:</label>
                        <div class="col-auto">
                            <input type="text" onclick="togglePercent(this, false)" onblur="togglePercent(this, true)" class="form-control col-sm-6" size="10" name="vars[ranksep]" id="ranksep" value="<?= $vars["ranksep"] ?>">
                        </div>
                        <label for="nodesep"><?= I18N::translate('Between individuals on the same level') ?>:</label>
                        <div class="col-auto">
                            <input type="text" onclick="togglePercent(this, false)" onblur="togglePercent(this, true)" class="form-control col-sm-6" size="10" name="vars[nodesep]" id="nodesep" value="<?= $vars["nodesep"] ?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <label class=" col-sm-4 col-form-label"><?= I18N::translate('Font') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="row">
                        <label for="typeface"><?= I18N::translate('Typeface') ?>:</label>
                        <div class="col-auto">
                            <?= view('components/select', ['name' => 'vars[typeface]', 'selected' => $vars['typeface'], 'options' => MainPage::updateTranslations($settings["typefaces"])]) ?>
                        </div>
                        <label for="fontsize_name"><?= I18N::translate('Font size for names') ?>:</label>
                        <div class="col-auto">
                            <input type="text" class="form-control col-sm-6" size="10" name="vars[fontsize_name]" id="fontsize_name" value="<?= $vars["fontsize_name"] ?>">
                        </div>
                        <label for="fontsize"><?= I18N::translate('Font size for details') ?>:</label>
                        <div class="col-auto">
                            <input type="text" class="form-control col-sm-6" size="10" name="vars[fontsize]" id="fontsize" value="<?= $vars["fontsize"] ?>">
                        </div>
                        <div>
                            <input type="color" class="picker" name="vars[fontcolor_name]" id="fontcolor_name" value="<?= $vars["fontcolor_name"] ?>" /><label for="fontcolor_name" class="picker-label"><?= I18N::translate('Font color for names') ?></label>
                        </div>

                        <div>
                            <input type="color" class="picker" name="vars[fontcolor_details]" id="fontcolor_details" value="<?= $vars["fontcolor_details"] ?>" /><label for="fontcolor_details" class="picker-label"><?= I18N::translate('Font color for details') ?></label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <label class=" col-sm-4 col-form-label"><?= I18N::translate('Relationship arrows') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[arrow_default]" id="arrow_default" value="<?= $vars["arrow_default"] ?>" /><label for="arrow_default" class="picker-label"><?= I18N::translate('Arrow color') ?></label>
                    </div>
                    <input type="hidden" name="vars[color_arrow_related]" value="no">
                    <input type="checkbox" name="vars[color_arrow_related]" id="color_arrow_related" value="color_arrow_related" <?= $vars["color_arrow_related"] == "color_arrow_related" ? 'checked' : '' ?>><label for="color_arrow_related" class="check-list"><?= I18N::translate('Show blood relationship in different color') ?></label>

                    <div id="arrow_group" class="color_subgroup col-auto wt-page-options-value">
                        <div class="sub-group">
                            <input type="color" class="picker" name="vars[arrow_related]" id="arrow_related" value="<?= $vars["arrow_related"] ?>" /><label for="arrow_related" class="picker-label"><?= I18N::translate('Related by birth') ?></label>
                            <input type="color" class="picker" name="vars[arrow_not_related]" id="arrow_not_related" value="<?= $vars["arrow_not_related"] ?>" /><label for="arrow_not_related" class="picker-label"><?= I18N::translate('Related other than by birth') ?></label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <label class=" col-sm-4 col-form-label"><?= I18N::translate('Tile colors') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorm]" id="colorm" value="<?= $vars["colorm"] ?>" /><label for="colorm" class="picker-label"><?= I18N::translate('Male individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorf]" id="colorf" value="<?= $vars["colorf"] ?>" /><label for="colorf" class="picker-label"><?= I18N::translate('Female individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorx]" id="colorx" value="<?= $vars["colorx"] ?>" /><label for="colorx" class="picker-label"><?= I18N::translate('Other gender individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[coloru]" id="coloru" value="<?= $vars["coloru"] ?>" /><label for="coloru" class="picker-label"><?= I18N::translate('Unknown gender individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorm_nr]" id="colorm_nr" value="<?= $vars["colorm_nr"] ?>" /><label for="colorm_nr" class="picker-label"><?= I18N::translate('Not blood-related male individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorf_nr]" id="colorf_nr" value="<?= $vars["colorf_nr"] ?>" /><label for="colorf_nr" class="picker-label"><?= I18N::translate('Not blood-related female individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorx_nr]" id="colorx_nr" value="<?= $vars["colorx_nr"] ?>" /><label for="colorx_nr" class="picker-label"><?= I18N::translate('Not blood-related other gender individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[coloru_nr]" id="coloru_nr" value="<?= $vars["coloru_nr"] ?>" /><label for="coloru_nr" class="picker-label"><?= I18N::translate('Not blood-related unknown gender individuals') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorindibg]" id="colorindibg" value="<?= $vars["colorindibg"] ?>" /><label for="colorindibg" class="picker-label"><?= I18N::translate('Individual background color') ?></label>
                    </div>
                    <input type="hidden" name="vars[startcol]" value="false">
                    <input type="checkbox" name="vars[startcol]" id="startcol" value="true" <?= $vars["startcol"] == "true" ? 'checked' : '' ?>><label for="startcol" class="check-list"><?= I18N::translate('Show starting persons in different color') ?></label>
                    <div class="col-auto" id="startcol_option">
                        <input type="color" class="picker" name="vars[colorstartbg]" id="colorstartbg" value="<?= $vars["colorstartbg"] ?>" /><label for="colorstartbg" class="picker-label"><?= I18N::translate('Starting persons background color') ?></label>
                    </div>
                </div>
            </div>
            <div class="row">
                <label class=" col-sm-4 col-form-label"><?= I18N::translate('Other colours') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorfam]" id="colorfam" value="<?= $vars["colorfam"] ?>" /><label for="colorfam" class="picker-label"><?= I18N::translate('Family background') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorborder]" id="colorborder" value="<?= $vars["colorborder"] ?>" /><label for="colorborder" class="picker-label"><?= I18N::translate('Outline colour') ?></label>
                    </div>
                    <div class="col-auto">
                        <input type="color" class="picker" name="vars[colorbg]" id="colorbg" value="<?= $vars["colorbg"] ?>" /><label for="colorbg" class="picker-label"><?= I18N::translate('Diagram background color') ?></label>
                    </div>
                </div>
            </div>
            <h3><?= /* I18N: Appearance heading */ I18N::translate('File Settings') ?></h3>
            <div class="row">
                <label class="col-sm-4 col-form-label" for="otype"><?= I18N::translate('Output File Type') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <?= view('components/select', ['name' => 'vars[otype]', 'selected' => $vars['otype'], 'options' => $otypes]) ?>
                </div>
                <label class="col-sm-4 col-form-label"><?= I18N::translate('Browser render') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <label for="auto_update"><?= I18N::translate('Auto-update') ?></label>
                    <input type="hidden" name="vars[auto_update]" value="no">
                    <input type="checkbox" name="vars[auto_update]" id="auto_update" value="auto_update" <?= $vars["auto_update"] == "auto_update" ? 'checked' : '' ?>>
                </div>
            </div>
            <h3><?= I18N::translate('Debug') ?></h3>
            <div class="row form-group">
                <label class="col-sm-4 col-form-label"><?= I18N::translate('Debug mode') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <label for="debug"><?= I18N::translate('Show debug panel') ?></label>
                    <input type="hidden" name="vars[show_debug]" value="no">
                    <input type="checkbox" name="vars[show_debug]" id="show_debug" value="show_debug" <?= $vars["show_debug"] == "show_debug" ? 'checked' : '' ?>><br>
                </div>
                <label class="col-sm-4 col-form-label" for="debug"><?= I18N::translate('Debug mode') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <label for="debug"><?= I18N::translate('Enable debug mode') ?></label>
                    <input type="hidden" name="vars[debug]" value="no">
                    <input type="checkbox" name="vars[debug]" id="debug" value="debug" <?= $vars["debug"] == "debug" ? 'checked' : '' ?>><br>
                </div>
                <label class="col-sm-4 col-form-label" for="use_graphviz"><?= I18N::translate('Graphviz') ?></label>
                <div class="col-sm-8 wt-page-options-value">
                    <label for="use_graphviz"><?= I18N::translate('Use Graphviz on server') ?></label>
                    <input type="hidden" name="vars[use_graphviz]" value="no">
                    <input type="checkbox" name="vars[use_graphviz]" id="use_graphviz" value="use_graphviz" onclick="setGraphvizAvailable(this.value==='use_graphviz');" <?= $vars["use_graphviz"] == "use_graphviz" ? 'checked' : '' ?> <?= isset($settings['graphviz_faked'])  ? "" : "disabled"; ?>><br></div>
            </div>
        </div>

        <input type="hidden" name="save" id="save" value="1">
        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('save') ?>
        </button>
        <a href="<?= $module->getConfigLink() . "?reset=1"; ?>" class="btn btn-outline-secondary"><?= I18N::translate('reset to defaults') ?></a>
    </form>
</div>