<?php

namespace vendor\WebtreesModules\gvexport;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;

/**
 * @var string      $title                  title of this page
 * @var array       $vars                   array of saved settings
 * @var array       $otypes                 output file type options
 * @var ?           $module                 this module
 */
$settingsObj = new Settings();
$settings = $settingsObj->getDefaultSettings();
$usegraphviz = $vars['graphviz_bin'] != "";
?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>
<p><?= I18N::translate('Values here are used as default values for new users of GVExport, and are used when users choose to reset the settings.'); ?></p>
<script src="<?= $module->assetUrl('javascript/gvexport.js'); ?>"></script>
<script type="text/javascript">
    let Url;
    import('<?= $module->assetUrl('javascript/MainPage/Url.js'); ?>').then((module)=>{
        Url = new module.Url();
        Url.removeURLParameter('reset');
    })
</script>
<link href="<?= $module->assetUrl('css/gvexport.css'); ?>" rel="stylesheet">

<div class="mb-5">
    <form method="post">
        <?= csrf_field() ?>
        <input type="hidden" name="vars[admin_page]" value="true"/>
        <h2><?= I18N::translate('Settings for GVExport'); ?></h2>
        <div class="row form-group">
            <label class="col-sm-4 col-form-label"><?= I18N::translate('Administrator settings') ?></label>
            <div class="col-sm-8 options-panel-background">
                <label for="filename"><?= I18N::translate('Download file name') ?>:</label>
                <input class="form-control col-sm-6" type="text" name="vars[filename]" id="filename" value="<?= e($vars["filename"]) ?>">
                <label for="mclimit"><?= I18N::translate('Graphviz MCLIMIT setting') ?>:</label>
                <input class="form-control col-sm-6" type="text" name="vars[mclimit]" id="mclimit" value="<?= I18N::digits($vars["mclimit"]); ?>">
                <label for="birth_prefix"><?= I18N::translate('Birthdate prefix') ?>:</label>
                <input class="form-control col-sm-6" type="text" name="vars[birth_prefix]" id="birth_prefix" pattern="^[A-Za-z0-9_ .*+()^%$#@!†∞-]*$" title="<?= I18N::translate('Letters, numbers, spaces, or the following symbols: ') . "_.*+()^%$#@!†∞-"; ?>" value="<?= e($vars["birth_prefix"]); ?>">
                <label for="death_prefix"><?= I18N::translate('Death date prefix') ?>:</label>
                <input class="form-control col-sm-6" type="text" name="vars[death_prefix]" id="death_prefix" pattern="^[A-Za-z0-9_ .*+()^%$#@!†∞-]*$" title="<?= I18N::translate('Letters, numbers, spaces, or the following symbols: ') . "_.*+()^%$#@!†∞-"; ?>" value="<?= e($vars["death_prefix"]); ?>">
                <label for="marriage_prefix"><?= I18N::translate('Marriage date prefix') ?>:</label>
                <input class="form-control col-sm-6" type="text" name="vars[marriage_prefix]" id="marriage_prefix" pattern="^[A-Za-z0-9_ .*+()^%$#@!†∞-]*$" title="<?= I18N::translate('Letters, numbers, spaces, or the following symbols: ') . "_.*+()^%$#@!†∞-"; ?>" value="<?= e($vars["marriage_prefix"]); ?>">
            </div>
            <hr>
            <label class="col-sm-4 col-form-label"><?= I18N::translate('Limit ancestor and descendant levels') ?></label>
            <div class="col-sm-8 options-panel-background">
                <?php
                    foreach (Settings::USER_ROLES as $role) {
                ?>
                <div>
                    <label for="limit_levels_<?= strtolower($role); ?>"><?= I18N::translate($role) ?>:</label>
                    <input type="number" min="0" max="99" class="form-control max-level-box" size="3" name="vars[limit_levels_<?= strtolower($role); ?>]" id="limit_levels_<?= strtolower($role); ?>" value="<?= I18N::digits($vars["limit_levels_" . strtolower($role)]); ?>">
                </div>
                <?php
                    }
                ?>
            </div>
        </div>

        <h2><?= I18N::translate('Default values for GVExport'); ?></h2>

        <div>
            <h3><?= I18N::translate('People to be included') ?></h3>
            <div class="row no-right-margin form-group">
                <?php
                // Include the "People to be included" section of the settings
                echo view($module->name() . '::ControlPanel/PeopleToInclude',
                    [
                        'vars' => $vars,
                        'module' => $module,
                        'settings' => $settings,
                        'admin' => true
                    ]); ?>
            </div>
            <hr>
            <h3><?= I18N::translate('Appearance') ?></h3>
            <div class="row no-right-margin form-group">
                <?php
                // Include the "People to be included" section of the settings
                echo view($module->name() . '::ControlPanel/Appearance',
                    [
                        'vars' => $vars,
                        'module' => $module,
                        'settings' => $settings,
                        'usegraphviz' => $usegraphviz,
                        'admin' => true
                    ]); ?>
            </div>
            <h3><?= I18N::translate('General Settings') ?></h3>
            <div class="row no-right-margin form-group">
                <?php
                // Include the "People to be included" section of the settings
                echo view($module->name() . '::ControlPanel/GeneralSettings',
                    [
                        'vars' => $vars,
                        'module' => $module,
                        'settings' => $settings,
                        'usegraphviz' => $usegraphviz,
                        'otypes' => $otypes,
                        'admin' => true
                    ]); ?>
            </div>
            <h3><?= I18N::translate('Debug') ?></h3>
            <div class="row no-right-margin form-group">
                <?php
                // Include the "People to be included" section of the settings
                echo view($module->name() . '::ControlPanel/DebugPanel',
                    [
                        'vars' => $vars,
                        'admin' => true
                    ]); ?>
            </div>
        </div>

        <input type="hidden" name="save" id="save" value="1">
        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('save') ?>
        </button>
        <?php $configLink = $module->getConfigLink();
            $resetLink = $configLink . (strpos($configLink, '?') ? "&" : "?") . "reset=1";
        ?>
        <a href="<?= $resetLink ?>" class="btn btn-outline-secondary"><?= I18N::translate('reset to defaults') ?></a>
    </form>
</div>
<script src="<?= $module->assetUrl('javascript/MainPage/Form.js'); ?>"></script>
