<?php

/**
 * This is the help sidebar home content
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\Help;

?>

<h2 class="help-title"><?= I18N::translate('Help'); ?></h2>
<p>
    <?= I18N::translate('This help contains detailed information on the options available in GVExport. You can navigate by clicking the options below, searching using the magnifying glass icon above, or by clicking on a setting to show the information for that setting.'); ?>
</p>
<ul>
    <li><a class="pointer help-item" data-name="<?= HELP::GETTING_STARTED; ?>"><?= I18N::translate(HELP::GETTING_STARTED); ?></a></li>
    <li><a class="pointer help-item" data-name="<?= HELP::ABOUT; ?>"><?= Help::ABOUT; ?></a></li>
    <li>
        <a class="pointer help-item">Detailed information</a>
        <ul>
            <li><a class="pointer help-item" data-name="<?= Help::PEOPLE_TO_INCLUDE; ?>"><?= I18N::translate(HELP::PEOPLE_TO_INCLUDE); ?></a> </li>
            <li><a class="pointer help-item" data-name="<?= Help::APPEARANCE; ?>"><?= I18N::translate(Help::APPEARANCE); ?></a> </li>
            <li><a class="pointer help-item" data-name="<?= Help::GENERAL_SETTINGS; ?>"><?= I18N::translate(Help::GENERAL_SETTINGS); ?></a> </li>
        </ul>
    </li>
</ul>