<?php

/**
 * This is part of the help sidebar content
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\Help;

?>

<h2 class="help-title"><?= Help::NAME_PEOPLE_TO_INCLUDE ?></h2>
<p>
    <?= I18N::translate('The "People to include" section lets you choose criteria for who to include in the diagram. Within this section, there are several setting groups'); ?>:
</p>
<ul>
    <li><a class="pointer help-item" data-name="<?= Help::NAME_INCLUDE_RELATED_TO; ?>"><?= I18N::translate(Help::NAME_INCLUDE_RELATED_TO); ?></a></li>
</ul>