<?php

use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;

/**
 * @var array       $vars                   array of saved settings
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 */
?>

<?= MainPage::addLabel('auto_update', 'Browser render', !$admin); ?>
<div class="col-sm-8 wt-page-options-value">
    <input type="checkbox" <?php if (!$admin) echo 'onclick="toggleUpdateButton()"'; ?> name="vars[auto_update]" id="auto_update" value="auto_update" <?= $vars["auto_update"] ? 'checked' : '' ?>>
    <label for="auto_update"><?= I18N::translate('Auto-update') ?></label>
</div>