<?php
use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\MainPage;

/**
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 */

?>

<?= MainPage::addLabel('message_history', 'Message history', !$admin); ?>
<div class="col-sm-8 options-panel-background">
    <button class="btn btn-outline-secondary" type="button" name="message_history" onclick="return showHelp('message_history');"><?= I18N::translate('View message history') ?></button>
</div>