<?php
use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\MainPage;

/**
 * @var bool        $show_help              whether to show help icons
 */

?>

<?= MainPage::addLabel('message_history', 'Message history', $show_help); ?>
<div class="col-sm-8 wt-page-options-value">
    <button class="btn btn-outline-secondary" type="button" name="message_history" onclick="return showHelp('message_history');"><?= I18N::translate('View message history') ?></button>
</div>