<?php

use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;

/**
 * @var array       $vars                   array of saved settings
 * @var bool        $usegraphviz            whether Graphviz is installed on the server and enabled
 * @var array       $settings               array of saved settings
 * @var array       $otypes                 output file type options
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 */
?>

<?= MainPage::addLabel('', 'Output file', !$admin); ?>
<div class="col-sm-8 wt-page-options-value">
    <label for="output_type"><?= I18N::translate('Output file type') ?></label>
    <?= view('components/select', ['name' => 'vars[output_type]', 'id' => 'output_type', 'selected' => e($vars['output_type']), 'options' => $otypes]) ?>
    <small id="emailHelp" class="form-text text-muted"><?= $usegraphviz ? "" : I18N::translate('Options limited as Graphviz not installed on server') ?></small>
    <div id="server_pdf_subgroup" class="colour_subgroup col-auto wt-page-options-value" <?= !($vars["output_type"] == 'pdf' || $vars["output_type"] == 'svg') || !$usegraphviz ? 'style="display:none;"' : '' ?>>
        <div class="col-auto">
            <label for="photo_quality"><?= I18N::translate('Quality of JPG photos') ?></label>
            <?= view('components/select', ['name' => 'vars[photo_quality]', 'id' => 'photo_quality', 'selected' => e($vars['photo_quality']), 'options' => MainPage::updateTranslations($settings["photo_quality_options"])]) ?>
        </div>

        <input type="checkbox" name="vars[convert_photos_jpeg]" id="convert_photos_jpeg" value="convert_photos_jpeg" <?= $vars["show_photos"] ? 'checked' : '' ?>>
        <label for="convert_photos_jpeg" class="check-list width-80pc"><?= I18N::translate('Convert photos to JPG where possible') ?></label>
    </div>
</div>