<?php

use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;

/**
 * @var array       $vars           array of saved settings
 * @var array       $settings       wider array of settings and options
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 */
?>

<?= MainPage::addLabel('save_settings_name', 'Save settings', !$admin); ?>
<div class="col-sm-8 wt-page-options-value">
    <?php if (!$admin) { ?>
    <div id="settings_list">

    </div>
    <div class="input-group mt-1">
        <input type="text" class="form-control" name="vars[save_settings_name]" id="save_settings_name" placeholder="<?= I18N::translate('Settings name'); ?>">
        <div class="input-group-append">
            <button id="save_settings_button" type="button" class="btn btn-outline-secondary" onclick="Data.storeSettings.saveSettingsAdvanced()"><?= I18N::translate('Save') ?></button>
        </div>
    </div>
    <?php } ?>
    <label for="settings_sort_order" class="margin-top"><?= I18N::translate('Settings list sort order') ?></label>
    <?= view('components/select', ['name' => 'vars[settings_sort_order]', 'id' => 'settings_sort_order', 'selected' => e($vars['settings_sort_order']), 'options' => MainPage::updateTranslations($settings["settings_sort_order_options"])]) ?>
    <div class="col-auto margin-top ">
        <input type="checkbox" <?php if (!$admin) echo 'onclick="setSavedDiagramsPanel()"'; ?> name="vars[show_diagram_panel]" id="show_diagram_panel" value="show_diagram_panel" <?= $vars["show_diagram_panel"] ? 'checked' : '' ?>>
        <label for="show_diagram_panel"><?= I18N::translate('Show saved diagrams panel') ?></label>
    </div>
</div>