<?php

use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;

/**
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 */
?>

<?= MainPage::addLabel('', 'Settings file', !$admin); ?>
<div class="col-sm-8 options-panel-background">
    <label for="load_settings"><?= I18N::translate('Load settings from file') ?></label><br>
    <input id="load_settings" type="file" onchange="uploadSettingsFile(this)">
</div>