<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$name = Help::APPEARANCE;
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $name]); ?>

<p>
    <?= I18N::translate('The "Appearance" section lets you customise the look of the diagram. Within this section, there are several setting groups'); ?>:
</p>
<ul>
    <li><a class="pointer help-item" data-name="<?= Help::GRAPH_DIRECTION; ?>"><?= I18N::translate(Help::GRAPH_DIRECTION); ?></a></li>
    <li><a class="pointer help-item" data-name="<?= Help::DIAGRAM_TYPE; ?>"><?= I18N::translate(Help::DIAGRAM_TYPE); ?></a></li>
    <li><a class="pointer help-item" data-name="<?= Help::TILE_DESIGN; ?>"><?= I18N::translate(Help::TILE_DESIGN); ?></a></li>
    <li><a class="pointer help-item" data-name="<?= Help::TILE_CONTENTS; ?>"><?= I18N::translate(Help::TILE_CONTENTS); ?></a></li>
    <li><a class="pointer help-item" data-name="<?= Help::DIAGRAM_APPEARANCE; ?>"><?= I18N::translate(Help::DIAGRAM_APPEARANCE); ?></a></li>
</ul>