<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$name = Help::APPEARANCE;
$help = new Help();
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $name]); ?>

<p>
    <?= I18N::translate('The "Appearance" section lets you customise the look of the diagram. Within this section, there are several setting groups:'); ?>
</p>
<ul>
    <li><?= $help->getHelpLinkHtml(HELP::GRAPH_DIRECTION);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::DIAGRAM_TYPE);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::TILE_DESIGN);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::TILE_CONTENTS);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::DIAGRAM_APPEARANCE);?></li>
</ul>