<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$name = Help::PEOPLE_TO_INCLUDE;
$help = new Help();
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $name]); ?>

<p>
    <?= I18N::translate('The "People to include" section lets you choose criteria for who to include in the diagram. Within this section, there are several setting groups'); ?>:
</p>
<ul>
    <li><?= $help->getHelpLinkHtml(HELP::CLIPPINGS_CART);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::INCLUDE_RELATED_TO);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::CONNECTIONS_TO_INCLUDE);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::XREFs_OF_INDIVIDUALS);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::STOP_PROCESSING_ON);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::NON_RELATIVES);?></li>
    <li><?= $help->getHelpLinkHtml(HELP::TREATMENT_OF_SOURCE_INDIVIDUALS);?></li>
</ul>