<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$name = Help::SAVED_DIAGRAMS;
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $name]); ?>

<p>
    <?= I18N::translate('This panel is only shown when the "Show saved diagrams" option is enabled in the "Save settings" section. It has just the following option'); ?>:
</p>
<ul>
    <li><a class="pointer help-item" data-name="<?= Help::LIST_OF_DIAGRAMS; ?>"><?= I18N::translate(Help::LIST_OF_DIAGRAMS); ?></a></li>
</ul>
<p>
    <?= I18N::translate('Related links'); ?>:
</p>
<ul>
    <li><a class="pointer help-item" data-name="<?= Help::SAVE_SETTINGS; ?>"><?= I18N::translate(Help::SAVE_SETTINGS); ?></a></li>
</ul>