<?php

use vendor\WebtreesModules\gvexport\GVExport;

/**
 * @var array       $vars           array of saved settings
 * @var GVExport    $module         this module
 * @var array       $settings       wider array of settings and options
 * @var bool        $usegraphviz     Whether Graphviz is installed on the server and enabled
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 */

?>

<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/Appearance/GraphDirection',['vars' => $vars, 'settings' => $settings, 'admin' => $admin]); ?>
</div>
<hr>
<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/Appearance/DiagramType',['vars' => $vars, 'admin' => $admin]); ?>
</div>
<hr>
<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/Appearance/TileDesign',['module' => $module, 'vars' => $vars, 'settings' => $settings, 'admin' => $admin]); ?>
</div>
<hr>
<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/Appearance/TileContents',['vars' => $vars, 'settings' => $settings, 'usegraphviz' => $usegraphviz, 'admin' => $admin]); ?>
</div>
<hr>
<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/Appearance/DiagramAdvanced',['vars' => $vars, 'admin' => $admin]); ?>
</div>