<?php

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;

/**
 * @var array $vars array of saved settings
 * @var GVExport $module this module
 * @var array $settings wider array of settings and options
 * @var bool $usegraphviz Whether Graphviz is installed on the server and enabled
 * @var array $otypes List of output file types
 */

?>

<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/GeneralSettings/OutputFile', ['vars' => $vars, 'settings' => $settings, 'usegraphviz' => $usegraphviz, 'otypes' => $otypes, 'show_help' => false]); ?>
</div>
<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/GeneralSettings/BrowserRender', ['vars' => $vars, 'show_help' => false]); ?>
</div>
<div class="row no-right-margin form-group">
    <?= view($module->name() . '::MainPage/GeneralSettings/SaveSettings', ['vars' => $vars, 'show_help' => false]); ?>
</div>