<?php
use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;

/**
 * @var array       $vars           array of saved settings
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 */

?>

<?= MainPage::addLabel('', 'Diagram type', !$admin); ?>
<div class="col-sm-8 options-panel-background">
    <div class="row">
        <?php // Simple diagram type no longer exists, but we need to handle it if we find the setting in loaded settings
        MainPage::handleSimpleSettings($vars['diagram_type']); ?>
        <div class="col-auto">
            <input type="radio" name="vars[diagram_type]" id="diagtype_decorated" value="decorated" <?= $vars["diagram_type"] == "decorated" ? 'checked' : '' ?>>
            <label for="diagtype_decorated"><?= I18N::translate('Separated') ?></label>
        </div>
        <div class="col-auto">
            <input type="radio" name="vars[diagram_type]" id="diagtype_combined" value="combined" <?= $vars["diagram_type"] == "combined" ? 'checked' : '' ?>>
            <label for="diagtype_combined"><?= I18N::translate('Combined') ?></label>
        </div>
    </div>
</div>
