<?php

use Fisharebest\Webtrees\Tree;
use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\Person;
use vendor\WebtreesModules\gvexport\Settings;

/**
 * @var array       $vars                   array of saved settings
 * @var array       $settings               wider array of settings and options
 * @var Tree        $tree                   webtrees Tree object of current tree
 * @var bool        $admin                  whether this is for the admin page (remove functions that aren't settings)
 */

?>

<?= MainPage::addLabel('', 'Tile design', !$admin); ?>
<div class="col-sm-8 wt-page-options-value">
    <div onclick="showHideSubgroup('shape_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Shape'); ?></div>
    <div id="shape_subgroup" class="setting_subgroup col-auto wt-page-options-value" style="display: none">
        <div class="col-auto">
            <label for="indi_tile_shape"><?= I18N::translate('Individual tile shape') ?></label>
            <?= view('components/select', ['name' => 'vars[indi_tile_shape]', 'id' => 'indi_tile_shape', 'selected' => e($vars['indi_tile_shape']), 'options' => MainPage::updateTranslations($settings["indi_tile_shape_options"])]) ?>
            <div id="shape_sex_subgroup" class="setting_subgroup col-auto wt-page-options-value fit-content margin-top" <?= !$admin && $vars["indi_tile_shape"] != Person::TILE_SHAPE_SEX ? 'style="display:none;"' : '' ?>>
                <div>
                    <label for="shape_sex_male"><?= I18N::translate('Male') ?></label>
                    <?= view('components/select', ['name' => 'vars[shape_sex_male]', 'id' => 'shape_sex_male', 'selected' => e($vars['shape_sex_male']), 'options' => MainPage::updateTranslations($settings["indi_tile_shape_sex_options"])]) ?>
                </div>
                <div>
                    <label for="shape_sex_female"><?= I18N::translate('Female') ?></label>
                    <?= view('components/select', ['name' => 'vars[shape_sex_female]', 'id' => 'shape_sex_female', 'selected' => e($vars['shape_sex_female']), 'options' => MainPage::updateTranslations($settings["indi_tile_shape_sex_options"])]) ?>
                </div>
                <div>
                    <label for="shape_sex_other"><?= I18N::translate('Other') ?></label>
                    <?= view('components/select', ['name' => 'vars[shape_sex_other]', 'id' => 'shape_sex_other', 'selected' => e($vars['shape_sex_other']), 'options' => MainPage::updateTranslations($settings["indi_tile_shape_sex_options"])]) ?>
                </div>
                <div>
                    <label for="shape_sex_unknown"><?= I18N::translate('Unknown') ?></label>
                    <?= view('components/select', ['name' => 'vars[shape_sex_unknown]', 'id' => 'shape_sex_unknown', 'selected' => e($vars['shape_sex_unknown']), 'options' => MainPage::updateTranslations($settings["indi_tile_shape_sex_options"])]) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-auto">
        <?php
        if (isset($tree)) {
            $images_enabled = ($tree->getPreference('SHOW_HIGHLIGHT_IMAGES') == '1');
        } else {
            $images_enabled = true;
        }
        if ($images_enabled) { ?>
        <div onclick="showHideSubgroup('photos_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Photos'); ?></div>
        <div id="photos_subgroup" class="setting_subgroup col-auto wt-page-options-value" style="display: none">
            <div class="col-sm-8">
                <input type="checkbox" onclick="showHideMatchCheckbox('show_photos', 'photos_enabled_subgroup');" name="vars[show_photos]" id="show_photos" value="show_photos" <?= $vars["show_photos"] ? 'checked' : '' ?>>
                <label for="show_photos"><?= I18N::translate('Show photos') ?></label>
                <div id="photos_enabled_subgroup" class="setting_subgroup col-auto wt-page-options-value" <?= !$admin && !$vars["show_photos"] ? 'style="display:none;"' : '' ?>>
                    <div class="col-auto">
                        <label for="photo_shape"><?= I18N::translate('Photo shape') ?></label>
                        <?= view('components/select', ['name' => 'vars[photo_shape]', 'id' => 'photo_shape', 'selected' => e($vars['photo_shape']), 'options' => MainPage::updateTranslations($settings["photo_shape_options"])]) ?>
                    </div>
                    <div class="col-auto">
                        <label for="photo_size"><?= I18N::translate('Photo size') ?></label>
                        <input type="text" onclick="togglePercent(this, false)" onblur="togglePercent(this, true)" class="form-control col-sm-6" size="10" name="vars[photo_size]" id="photo_size"
                               value="<?= e($vars["photo_size"]) ?>">
                    </div>
                    <div class="col-auto">
                        <label for="photo_resolution"><?= I18N::translate('Photo resolution') ?></label>
                        <input type="text" onclick="togglePercent(this, false)" onblur="togglePercent(this, true)" class="form-control col-sm-6" size="10" name="vars[photo_resolution]" id="photo_resolution"
                               value="<?= e($vars["photo_resolution"]) ?>">
                    </div>
                </div>
            </div>
        </div>
        <?php } ?>
        <div onclick="showHideSubgroup('colours_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Colours'); ?></div>
        <div id="colours_subgroup" class="setting_subgroup col-auto wt-page-options-value" style="display: none">
            <div class="col-auto margin-bottom">
                <label for="bg_col_type"><?= I18N::translate('Individual background colour') ?></label>
                <?= view('components/select', ['name' => 'vars[bg_col_type]', 'id' => 'bg_col_type', 'selected' => e($vars['bg_col_type']), 'options' => MainPage::updateTranslations($settings["bg_col_type_options"])]) ?>
                <div id="custom_bg_subgroup" class="setting_subgroup col-auto wt-page-options-value fit-content margin-top"<?= !$admin && $vars["bg_col_type"] != Settings::OPTION_BACKGROUND_CUSTOM_COLOUR ? 'style="display:none;"' : '' ?>>
                    <input type="color" class="picker" name="vars[indi_background_col]" id="indi_background_col" value="<?= e($vars["indi_background_col"]); ?>" /><label for="indi_background_col" class="picker-label"><?= I18N::translate('Custom background colour') ?></label>
                </div>
                <div id="vitals_bg_subgroup" class="setting_subgroup col-auto wt-page-options-value fit-content margin-top" <?= !$admin && $vars["bg_col_type"] != Settings::OPTION_BACKGROUND_VITAL_COLOUR ? 'style="display:none;"' : '' ?>>
                    <input type="color" class="picker" name="vars[indi_background_dead_col]" id="indi_background_dead_col" value="<?= e($vars["indi_background_dead_col"]); ?>" /><label for="indi_background_dead_col" class="picker-label"><?= I18N::translate('Deceased') ?></label>
                    <input type="color" class="picker" name="vars[indi_background_living_col]" id="indi_background_living_col" value="<?= e($vars["indi_background_living_col"]); ?>" /><label for="indi_background_living_col" class="picker-label"><?= I18N::translate('Living') ?></label>
                </div>
            </div>
            <div class="col-auto margin-bottom">
                <label for="stripe_col_type"><?= I18N::translate('Individual stripe color') ?></label>
                <?= view('components/select', ['name' => 'vars[stripe_col_type]', 'id' => 'stripe_col_type', 'selected' => e($vars['stripe_col_type']), 'options' => MainPage::updateTranslations($settings["stripe_col_type_options"])]) ?>
                <div id="vitals_stripe_subgroup" class="setting_subgroup col-auto wt-page-options-value fit-content margin-top" <?= !$admin && $vars["stripe_col_type"] != Settings::OPTION_STRIPE_VITAL_COLOUR ? 'style="display:none;"' : '' ?>>
                    <input type="color" class="picker" name="vars[indi_stripe_dead_col]" id="indi_stripe_dead_col" value="<?= e($vars["indi_stripe_dead_col"]); ?>" /><label for="indi_stripe_dead_col" class="picker-label"><?= I18N::translate('Deceased') ?></label>
                    <input type="color" class="picker" name="vars[indi_stripe_living_col]" id="indi_stripe_living_col" value="<?= e($vars["indi_stripe_living_col"]); ?>" /><label for="indi_stripe_living_col" class="picker-label"><?= I18N::translate('Living') ?></label>
                </div>
            </div>
            <div class="col-auto margin-bottom">
                <label for="border_col_type"><?= I18N::translate('Individual border color') ?></label>
                <?= view('components/select', ['name' => 'vars[border_col_type]', 'id' => 'border_col_type', 'selected' => e($vars['border_col_type']), 'options' => MainPage::updateTranslations($settings["border_col_type_options"])]) ?>
                <div id="custom_border_subgroup" class="setting_subgroup col-auto wt-page-options-value fit-content margin-top" <?= !$admin && $vars["border_col_type"] != Settings::OPTION_BORDER_CUSTOM_COLOUR ? 'style="display:none;"' : '' ?>>
                    <input type="color" class="picker" name="vars[indi_border_col]" id="indi_border_col" value="<?= e($vars["indi_border_col"]); ?>" /><label for="indi_border_col" class="picker-label"><?= I18N::translate('Custom border colour') ?></label>
                </div>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[male_col]" id="male_col" value="<?= e($vars["male_col"]); ?>" /><label for="male_col" class="picker-label"><?= I18N::translate('Male individuals') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[female_col]" id="female_col" value="<?= e($vars["female_col"]); ?>" /><label for="female_col" class="picker-label"><?= I18N::translate('Female individuals') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[other_gender_col]" id="other_gender_col" value="<?= e($vars["other_gender_col"]); ?>" /><label for="other_gender_col" class="picker-label"><?= I18N::translate('Other gender individuals') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[unknown_gender_col]" id="unknown_gender_col" value="<?= e($vars["unknown_gender_col"]); ?>" /><label for="unknown_gender_col" class="picker-label"><?= I18N::translate('Unknown gender individuals') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[male_unrelated_col]" id="male_unrelated_col" value="<?= e($vars["male_unrelated_col"]); ?>" /><label for="male_unrelated_col" class="picker-label"><?= I18N::translate('Not blood-related male individuals') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[female_unrelated_col]" id="female_unrelated_col" value="<?= e($vars["female_unrelated_col"]); ?>" /><label for="female_unrelated_col" class="picker-label"><?= I18N::translate('Not blood-related female individuals') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[oth_gender_unrel_col]" id="oth_gender_unrel_col" value="<?= e($vars["oth_gender_unrel_col"]); ?>" /><label for="oth_gender_unrel_col" class="picker-label"><?= I18N::translate('Not blood-related other gender individuals') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[unkn_gender_unrel_col]" id="unkn_gender_unrel_col" value="<?= e($vars["unkn_gender_unrel_col"]); ?>" /><label for="unkn_gender_unrel_col" class="picker-label"><?= I18N::translate('Not blood-related unknown gender individuals') ?></label>
            </div>
            <div class="col-auto padding-left-10">
                <input type="checkbox" name="vars[highlight_start_indis]" onclick="toggleHighlightStartPersons(this.checked, <?= !$admin ? 'false' : 'true'; ?>)" id="highlight_start_indis" value="true" <?= $vars["highlight_start_indis"] ? 'checked' : '' ?>><label for="highlight_start_indis" class="check-list width-90pc"><?= I18N::translate('Show starting individuals in different colour') ?></label>
                <div class="setting_subgroup col-auto wt-page-options-value" id="startcol_option"  <?= !$admin && $vars["highlight_start_indis"] != "true" ? 'style="display:none;"' : '' ?>>
                    <input type="color" class="picker" name="vars[highlight_col]" id="highlight_col" value="<?= e($vars["highlight_col"]); ?>" /><label for="highlight_col" class="picker-label"><?= I18N::translate('Starting individuals background colour') ?></label>
                    <?php if (!$admin) { ?>
                        <label for="no_highlight_xref_list"><?= I18N::translate('Colour these individuals:'); ?></label><br>
                        <div id="highlight_list">

                        </div>
                        <input type="hidden" class="form-control" name="vars[no_highlight_xref_list]" id="no_highlight_xref_list" value="<?= e($vars['no_highlight_xref_list']); ?>">
                    <?php } ?>
                </div>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[family_col]" id="family_col" value="<?= e($vars["family_col"]); ?>" /><label for="family_col" class="picker-label"><?= I18N::translate('Family background') ?></label>
            </div>
            <div class="col-auto">
                <input type="color" class="picker" name="vars[border_col]" id="border_col" value="<?= e($vars["border_col"]); ?>" /><label for="border_col" class="picker-label"><?= I18N::translate('Family border colour') ?></label>
            </div>
        </div>
    </div>
    <div onclick="showHideSubgroup('font_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Font'); ?></div>
    <div id="font_subgroup" class="setting_subgroup col-auto wt-page-options-value" style="display: none">
        <div class="col-auto">
            <label for="typeface"><?= I18N::translate('Typeface') ?></label>
            <div class="col-auto">
                <?= view('components/select', ['name' => 'vars[typeface]', 'id' => 'typeface', 'selected' => I18N::digits($vars['typeface']), 'options' => MainPage::updateTranslations($settings["typefaces"])]) ?>
            </div>
            <label for="font_size_name"><?= I18N::translate('Font size for names') ?></label>
            <div class="col-auto">
                <input type="text" class="form-control col-sm-6" size="10" name="vars[font_size_name]" id="font_size_name" value="<?= I18N::digits($vars["font_size_name"]); ?>">
            </div>
            <label for="font_size"><?= I18N::translate('Font size for details') ?></label>
            <div class="col-auto">
                <input type="text" class="form-control col-sm-6" size="10" name="vars[font_size]" id="font_size" value="<?= I18N::digits($vars["font_size"]); ?>">
            </div>
            <div>
                <input type="color" class="picker" name="vars[font_colour_name]" id="font_colour_name" value="<?= e($vars["font_colour_name"]); ?>" /><label for="font_colour_name" class="picker-label"><?= I18N::translate('Font colour for names') ?></label>
            </div>

            <div>
                <input type="color" class="picker" name="vars[font_colour_details]" id="font_colour_details" value="<?= e($vars["font_colour_details"]); ?>" /><label for="font_colour_details" class="picker-label"><?= I18N::translate('Font colour for details') ?></label>
            </div>
        </div>
    </div>
</div>