<?php

use Fisharebest\Webtrees\Individual;
use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;

/**
 * @var array       $vars                   array of saved settings
 * @var array       $settings               wider array of settings and options
 * @var bool        $usegraphviz            whether Graphviz is installed on the server and enabled
 * @var Individual  $individual             webtrees Individual object
 * @var bool        $admin                  whether this is for the admin page (remove functions that aren't settings)
 */

?>

<?= MainPage::addLabel('', 'Tile contents', !$admin); ?>
<div class="col-sm-8 wt-page-options-value">
    <div class="col-auto">
        <div onclick="showHideSubgroup('url_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Page links'); ?></div>
        <div id="url_subgroup" class="colour_subgroup col-auto wt-page-options-value" style="display: none">
            <input type="checkbox" name="vars[add_links]" id="add_links" value="add_links" <?= $vars["add_links"] ? 'checked' : '' ?>>
            <label for="add_links"><?= I18N::translate('Add URL to individuals and families') ?></label>
            <br>
            <span class="text-muted">(<?= $usegraphviz ? I18N::translate('browser, SVG, and PDF only') : I18N::translate('browser and SVG only'); ?>)</span>
        </div>
    </div>
    <div class="col-auto">
        <div onclick="showHideSubgroup('abbreviations_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Abbreviations'); ?></div>
        <div id="abbreviations_subgroup" class="colour_subgroup col-auto wt-page-options-value" style="display: none">
            <div class="col-auto">
                <label for="use_abbr_name"><?= I18N::translate('Abbreviated names'); ?></label>
                <?= view('components/select', ['name' => 'vars[use_abbr_name]', 'id' => 'use_abbr_name', 'selected' => I18N::digits($vars['use_abbr_name']), 'options' => MainPage::updateTranslations($settings["use_abbr_names"])]) ?>
            </div>
            <div class="col-auto">
                <label for="use_abbr_name"><?= I18N::translate('Abbreviated place names'); ?></label>
                <?= view('components/select', ['name' => 'vars[use_abbr_place]', 'id' => 'use_abbr_place', 'selected' => I18N::digits($vars['use_abbr_place']), 'options' => MainPage::updateTranslations($settings["use_abbr_places"])]) ?>
            </div>
        </div>
    </div>
    <div class="col-auto">
        <div onclick="showHideSubgroup('indi_details_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Information on individuals'); ?></div>
        <div id="indi_details_subgroup" class="colour_subgroup col-auto wt-page-options-value" style="display: none">
            <div class="col-sm-8">
                <?php
                /* Check if another module (e.g. vesta classic) is adding the XREF to
                   the name. If so, we want to enable the XREF option for individuals
                   unless we already have a saved setting */
                if (isset($individual)) {
                    $startName = $individual->fullName();
                    $name = str_replace(" (" . $individual->xref() . ")", "", $startName);
                }
                if (isset($startName) && isset($name) && $startName != $name && isset($vars["first_run_xref_check"])) {
                    $overridePID = true;
                } else {
                    $overridePID = false;
                }
                ?>
                <input type="checkbox" name="vars[show_xref_individuals]" id="show_xref_individuals" value="show_xref_individuals" <?= $vars["show_xref_individuals"] || $overridePID ? 'checked' : '' ?>>
                <label for='show_xref_individuals'><?= I18N::translate('Show individual XREF'); ?></label>
            </div>
            <div class="col-sm-8">
                <input type="checkbox" onclick="showHideMatchCheckbox('show_birthdate', 'birth_date_subgroup');" name="vars[show_birthdate]" id="show_birthdate" value="show_birthdate" <?= $vars["show_birthdate"] ? 'checked' : '' ?>>
                <label for='show_birthdate'><?= I18N::translate('Show birthdate'); ?></label>
                <div id="birth_date_subgroup" class="colour_subgroup col-auto wt-page-options-value" <?= !$vars["show_birthdate"] ? 'style="display:none;"' : '' ?>>
                    <div class="col-auto mx-3">
                        <input type="radio" name="vars[birthdate_year_only]" id="bd_type_y" value="true" <?= $vars["birthdate_year_only"] ? 'checked' : '' ?>>
                        <label for="bd_type_y"><?= I18N::translate('Year') ?></label>
                    </div>
                    <div class="col-auto mx-3">
                        <input type="radio" name="vars[birthdate_year_only]" id="bd_type_gedcom" value="false" <?= !$vars["birthdate_year_only"] ? 'checked' : '' ?>>
                        <label for="bd_type_gedcom"><?= I18N::translate('Full date') ?></label>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <input type="checkbox" name="vars[show_birthplace]" id="show_birthplace" value="show_birthplace" <?= $vars["show_birthplace"] ? 'checked' : '' ?>>
                <label for='show_birthplace'><?= I18N::translate('Show birthplace'); ?></label>
            </div>

            <div class="col-sm-8">
                <input type="checkbox" onclick="showHideMatchCheckbox('show_death_date', 'death_date_subgroup');" name="vars[show_death_date]" id="show_death_date" value="show_death_date" <?= $vars["show_death_date"] ? 'checked' : '' ?>>
                <label for='show_death_date'><?= I18N::translate('Show death date'); ?></label>
                <div id="death_date_subgroup" class="colour_subgroup col-auto wt-page-options-value" <?= !$vars["show_death_date"] ? 'style="display:none;"' : '' ?>>
                    <div class="col-auto mx-3">
                        <input type="radio" name="vars[death_date_year_only]" id="dd_type_y" value="true" <?= $vars["death_date_year_only"] ? 'checked' : '' ?>>
                        <label for="dd_type_y"><?= I18N::translate('Year') ?></label>
                    </div>
                    <div class="col-auto mx-3">
                        <input type="radio" name="vars[death_date_year_only]" id="dd_type_gedcom" value="false" <?= !$vars["death_date_year_only"] ? 'checked' : '' ?>>
                        <label for="dd_type_gedcom"><?= I18N::translate('Full date') ?></label>
                    </div>
                </div>
            </div>

            <div class="col-sm-8">
                <input type="checkbox" name="vars[show_death_place]" id="show_death_place" value="show_death_place" <?= $vars["show_death_place"] ? 'checked' : '' ?>>
                <label for='show_death_place'><?= I18N::translate('Show death place'); ?></label>
            </div>
            <div class="col-sm-8">
                <input type="checkbox" name="vars[show_indi_sex]" id="show_indi_sex" value="show_indi_sex" <?= $vars["show_indi_sex"] ? 'checked' : '' ?>>
                <label for='show_indi_sex'><?= I18N::translate('Show sex of individuals'); ?></label>
            </div>
        </div>
    </div>
    <div class="col-auto">
        <div onclick="showHideSubgroup('fam_details_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Information on families'); ?></div>
        <div id="fam_details_subgroup" class="colour_subgroup col-auto wt-page-options-value" style="display: none">
            <div class="col-sm-8">
                <input type="checkbox" name="vars[show_xref_families]" id="show_xref_families" value="show_xref_families" <?= $vars["show_xref_families"] ? 'checked' : '' ?>>
                <label for='show_xref_families'><?= I18N::translate('Show family XREF'); ?></label>
            </div>
            <div class="col-sm-8">
                <input type="checkbox" onclick="showHideMatchCheckbox('show_marriage_date', 'marriage_date_subgroup');" name="vars[show_marriage_date]" id="show_marriage_date" value="show_marriage_date" <?= $vars["show_marriage_date"] ? 'checked' : '' ?>>
                <label for='show_marriage_date'><?= I18N::translate('Show marriage date'); ?></label>
                <div id="marriage_date_subgroup" class="colour_subgroup col-auto wt-page-options-value" <?= !$vars["show_marriage_date"] ? 'style="display:none;"' : '' ?>>
                    <div class="col-auto mx-3">
                        <input type="radio" name="vars[marr_date_year_only]" id="md_type_y" value="true" <?= $vars["marr_date_year_only"] ? 'checked' : '' ?>>
                        <label for="md_type_y"><?= I18N::translate('Year') ?></label>
                    </div>
                    <div class="col-auto mx-3">
                        <input type="radio" name="vars[marr_date_year_only]" id="md_type_gedcom" value="false" <?= !$vars["marr_date_year_only"] ? 'checked' : '' ?>>
                        <label for="md_type_gedcom"><?= I18N::translate('Full date') ?></label>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <input type="checkbox" name="vars[show_marriage_place]" id="show_marriage_place" value="show_marriage_place" <?= $vars["show_marriage_place"] ? 'checked' : '' ?>>
                <label for='show_marriage_place'><?= I18N::translate('Show marriage place'); ?></label>
            </div>
        </div>
    </div>
    <div class="col-auto">
    </div>
    <div class="col-auto">
    </div>
</div>