<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$page_name = Help::MESSAGE_HISTORY;
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $page_name]); ?>

<p>
    <?= I18N::translate('This button shows the history of the pop up notifications. Note that this history is not saved, so it is lost if you leave the page or the page is reloaded.'); ?>
</p>