<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$page_name = Help::SAVE_SETTINGS;
$help = new Help();
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $page_name]); ?>

<p>
    <?= I18N::translate('Here you are able to save the chosen settings within GVExport. The settings are only accessible within the same user and tree. Click a settings record to load it.'); ?>
</p>
<p>
    <?= I18N::translate('For example, you may have many diagrams you create from your tree. You may want to save the settings used for each diagram so that in future you can regenerate the diagram to include any new information.'); ?>
</p>
<p>
    <?= I18N::translate('If you click the ellipsis on a record, you will see several options.'); ?>
</p>
<ul>
    <li><?= I18N::translate('Delete'); ?> - <?= I18N::translate('remove these settings'); ?></li>
    <li><?= I18N::translate('Download'); ?> - <?= I18N::translate('download a file holding the settings, which can be loaded at a later date'); ?></li>
    <li><?= I18N::translate('Rename'); ?> - <?= I18N::translate('change the name of a saved setting'); ?></li>
    <li><?= I18N::translate('Copy link'); ?> - <?= I18N::translate('if logged in, this allows you to share the settings with others by creating a URL to share with them, which is copied to the clipboard of your device'); ?></li>
    <li><?= I18N::translate('Revoke link'); ?> - <?= I18N::translate('if a sharing link has been created, this will show to allow you to revoke the link, so it can no longer be accessed'); ?></li>
    <li><?= I18N::translate('Add to My favourites'); ?> - <?= I18N::translate('if logged in, this will create a sharing link and add this to the webtrees favourites on your &quot;My page&quot; page'); ?></li>
    <li><?= I18N::translate('Add to Tree favourites'); ?> - <?= I18N::translate('if logged in as a tree manager, this will create a sharing link and add this to the webtrees favourites on the tree home page'); ?></li>
</ul>
<p>
    <?= I18N::translate('When logged out, only the Delete and Download options will be available'); ?>.
</p>
<h4><?= I18N::translate('Settings list sort order'); ?></h4>
<p>
    <?= I18N::translate('This option lets you choose the order of saved settings. The options are'); ?>:
</p>
<ul>
    <li><?= I18N::translate('Oldest first'); ?> - <?= I18N::translate('The default option. New settings are added to the bottom of the list.'); ?></li>
</ul>
<ul>
    <li><?= I18N::translate('Newest first'); ?> - <?= I18N::translate('New settings are added to the top of the list.'); ?></li>
</ul>
<ul>
    <li><?= I18N::translate('Alphabetical order'); ?> - <?= I18N::translate('Settings are sorted based on their name.'); ?></li>
</ul>
<ul>
    <li><?= I18N::translate('Reverse alphabetical order'); ?> - <?= I18N::translate('Settings are sorted based on their name, but in reverse.'); ?></li>
</ul>
<p>
    <?= I18N::translate("Note that if you update a saved setting, this will affect how it is sorted under the 'Oldest first' or 'Newest first' options."); ?>
</p>
<h4><?= I18N::translate('Show saved diagrams panel'); ?></h4>
<p>
    <?= I18N::translate('The &quot;Show saved diagrams panel&quot; option adds a new section to the settings that makes the saved settings available as a dropdown list. You may wish to use webtrees&apos; ability for an administrator to &quot;Masquerade as user&quot; to set up some settings for another user, then enable this option, so they can easily choose different prepared diagrams without needed to delve into the advanced settings.'); ?>
</p>
<p>
    <?= I18N::translate('Related links'); ?>:
</p>
<ul>
    <li><?= $help->getHelpLinkHtml(HELP::SAVED_DIAGRAMS);?></li>
</ul>