<?php

use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;

/**
 * @var array       $vars                   array of saved settings
 * @var bool        $show_help              whether to show help icons
 */
?>

<?= MainPage::addLabel('mark_not_related', 'Non-relatives', $show_help); ?>
<div class="col-sm-8 wt-page-options-value">
    <input class="cart_toggle" onclick="showHideMatchCheckbox('mark_not_related', 'mark_related_subgroup');" type="checkbox" name="vars[mark_not_related]" id="mark_not_related" value="mark_not_related" <?= $vars["mark_not_related"] ? 'checked' : '' ?>>
    <label class="check-list width-90pc" for="mark_not_related"><?= I18N::translate('Mark not blood-related people with different color') ?></label>
    <div id="mark_related_subgroup" class="color_subgroup col-auto wt-page-options-value">
        <input class="cart_toggle" type="checkbox" name="vars[faster_relation_check]" id="faster_relation_check" value="faster_relation_check" <?= $vars["faster_relation_check"] ? 'checked' : '' ?>>
        <label class="check-list width-90pc" for="faster_relation_check"><?= I18N::translate('Ignore unseen links to speed up relative check') ?></label>
    </div>
</div>