<?php

use vendor\WebtreesModules\gvexport\MainPage;

/**
 * @var array       $vars                   array of saved settings
 * @var array       $settings               array of saved settings
 * @var bool        $show_help              whether to show help icons
 */
?>

<?= MainPage::addLabel('graph_dir', 'Treatment of source individuals'); ?>
<div class="col-sm-8 wt-page-options-value">
    <?= view('components/select', ['name' => 'vars[url_xref_treatment]', 'id' => 'url_xref_treatment', 'selected' => e($vars['url_xref_treatment']), 'options' => MainPage::updateTranslations($settings["url_xref_treatment_options"])]) ?>
</div>