<?php

use vendor\WebtreesModules\gvexport\MainPage;

/**
 * @var array       $vars                   array of saved settings
 * @var bool        $show_help              whether to show help icons
 */
?>
<?= MainPage::addLabel('xref_list', 'XREFs of included individuals', $show_help); ?>
<div class="col-sm-8 wt-page-options-value">
    <div class="input-group mt-1">
        <input type="text" class="form-control" name="vars[xref_list]" id="xref_list" value="<?= e($vars['xref_list']) ?>" onchange="refreshIndisFromXREFS(true)">
        <div class="input-group-append">
            <button type="button" class="btn btn-outline-secondary" onclick="refreshIndisFromXREFS(false)">⟳</button>
        </div>
    </div>
</div>