<?php

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Settings;

/**
 * @var GVExport    $module                 this module
 * @var array       $vars           array of saved settings
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 * @var string      $id             the ID of the subgroup div
 * @var string      $select_id      the ID of the dropdown list that shows this section
 * @var string      $option_id      the ID of the option that means this should be shown
 * @var array       $picker_list    list of colour pickers to create as key pairs (id => label)
 */
$age_low_id = 'indi_' . $group . '_age_low';
$age_high_id = 'indi_' . $group . '_age_high';
?>
<?= view($module->name() . '::MainPage/Appearance/TileDesign/ColourPickerList',['vars' => $vars, 'admin' => $admin, 'id' => 'subgroup_' . $group . '_age', 'select_id' => 'bg_col_type', 'option_id' => Settings::OPTION_BACKGROUND_AGE_COLOUR, 'picker_list' => [$age_low_id . '_col' => 'Low age colour', $age_high_id . '_col' => 'High age colour', 'indi_' . $group . '_age_unknown_col' => 'Unknown age colour']]); ?>

<div class="align-middle-container">
    <label for="<?= $age_low_id; ?>" class="col-sm-6"><?= I18N::translate('Age for low colour') ?></label>
    <input type="number" class="cart_toggle form-control max-level-box" size="3" name="vars[<?= $age_low_id; ?>]" id="<?= $age_low_id; ?>" value="<?= I18N::digits($vars[$age_low_id]); ?>">
</div>
<div class="align-middle-container">
    <label for="<?= $age_high_id; ?>" class="col-sm-6"><?= I18N::translate('Age for high colour') ?></label>
    <input type="number" class="cart_toggle form-control max-level-box" size="3" name="vars[<?= $age_high_id; ?>]" id="<?= $age_high_id; ?>" value="<?= I18N::digits($vars[$age_high_id]); ?>">
</div>