<?php
use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\Settings;

/**
 * @var array       $vars           array of saved settings
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 * @var string      $id             the ID of the subgroup div
 * @var string      $select_id      the ID of the dropdown list that shows this section
 * @var string      $option_id      the ID of the option that means this should be shown
 * @var array       $picker_list    list of colour pickers to create as key pairs (id => label)
 */

?>

<?php
    foreach ($picker_list as $picker_id => $label) {
?>
        <input type="color" class="picker" name="vars[<?= $picker_id; ?>]" id="<?= $picker_id; ?>" value="<?= e($vars[$picker_id]); ?>" /><label for="<?= $picker_id; ?>" class="picker-label"><?= I18N::translate($label) ?></label>
<?php
    }
?>