<?php

use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\I18N;


/**
 * @var string      $vars           string of view location to insert into subgroup* @var array       $view_options   options to pass to view. We also reuse some parts of this.
 * @var string      $tree           string of view location to insert into subgroup* @var array       $view_options   options to pass to view. We also reuse some parts of this.
 */

?>
<h1>Edit shared notes</h1>
<input type="color" class="picker" name="vars[sharednote_col]" id="sharednote_col" value="" /><label for="sharednote_col" class="picker-label"><?= I18N::translate('Shared note colour') ?></label>