<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module   The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$page_name = Help::DIAGRAM_APPEARANCE;
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader',['name' => $page_name]); ?>


<h4><?= I18N::translate('Diagram DPI'); ?></h4>
<p>
    <?= I18N::translate('For output such as JPG and PNG, the DPI setting will produce higher quality output when it is larger, but will also increase the file size. Smaller values will produce smaller files, but the quality will be worse and if the value is too low you may not be able to read text.'); ?>
</p>


<h4><?= I18N::translate('Spacing'); ?></h4>
<p>
<?= I18N::translate('These options affect the distance between nodes on the diagram.'); ?>
</p>
<h5><?= I18N::translate('Between generations'); ?></h5>
<p>
    <?= I18N::translate('How close you want generations on the output. For example, for left to right output, smaller numbers will bring the columns of individuals closer together, while larger numbers would push them further apart.'); ?>
</p>
<h5><?= I18N::translate('Between individuals on the same level'); ?>
</h5>
<p>
    <?= I18N::translate('How close you want the individuals of the same generation on the output. For example, for left to right output, smaller numbers will mean less space vertically between the boxes, while larger numbers would push them further apart.'); ?>
</p>


<h4><?= I18N::translate('Layout'); ?></h4>
<p>
    <?= I18N::translate('This section lets you change settings related to the layout of the diagram.'); ?>
</p>

<h5><?= I18N::translate('Partner position'); ?></h5>
<p>
    <?= I18N::translate('When you have selected the "Combined" layout option, this option lets you choose whether the partners should be shown size by side (default), or in Stacked mode, which places them on top of each other. Stacked mode reduces the width of the diagram, which can be helpful in some situations.'); ?>
</p>


<h4><?= I18N::translate('Diagram colours'); ?></h4>
<p>
    <?= I18N::translate('This section allows you to change colours associated with the diagram that are not directly related to the individual or family tiles. Click the coloured box to change the colour. This uses your browser&apos;s colour picker, so will look different depending on what browser you are using.'); ?>
</p>
<h5><?= I18N::translate('Diagram background colour'); ?></h5>
<p>
    <?= I18N::translate('This is the colour of the area behind the family tree.'); ?>
</p>
<h5><?= I18N::translate('Relationship arrow colour'); ?></h5>
<p>
    <?= I18N::translate('The colour of the arrows that show relationships between individuals and families.'); ?>
</p>
<h5><?= I18N::translate('Show blood relationship in different colour'); ?></h5>
<p>
<?= I18N::translate('This shows blood relationships in a different colour than other relationships (e.g. adoption). Selecting this option will provide two colours that can be customised'); ?>:
</p>
<ul>
    <li><?= I18N::translate('Related by birth'); ?> - <?= I18N::translate('The arrow colour to use for children related by birth'); ?></li>
    <li><?= I18N::translate('Related other than by birth'); ?> - <?= I18N::translate('The arrow colour to use for children not related by birth'); ?></li>
</ul>