<?php

/**
 * This is part of the help sidebar content
 *
 * @var GVExport $module The instance of this module from webtrees
 */

use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\Help;

$page_name = Help::TILE_CONTENTS;
$help = new Help();
?>

<?= view($module->name() . '::MainPage/Help/HelpHeader', ['name' => $page_name]); ?>

<p>
    <?= I18N::translate('This section allows for some changes to the content of tiles, including links, abbreviations, and the details included on individuals and families.'); ?>
</p>
<h4><?= I18N::translate('Page links'); ?></h4>
<h5><?= I18N::translate('Add URL to individuals and families'); ?></h5>
<p>
    <?= I18N::translate('For SVG (and PDF if Graphviz installed on server) output, links can be included. This way you can click on the person in the diagram to be taken to their webtrees page.'); ?>
</p>
<p>
    <?= I18N::translate('This also affects families in the diagram. If this option is enabled, you can click on family records to open the family webtrees page. Also see \'Action when individual clicked\' in the Browser render settings.'); ?>
</p>
<p>
    <?= I18N::translate('Note that SVG output will always be rendered by the browser (and not the server) if you choose to include page links.'); ?>
</p>
<h4><?= I18N::translate('Abbreviations'); ?></h4>
<h5><?= I18N::translate('Abbreviated names'); ?></h5>
<p>
    <?= I18N::translate('There are several options to shorten the names of individuals displayed.'); ?>
</p>
<ul>
    <li><?= I18N::translate('Full name'); ?> - <?= I18N::translate('the default option, this shows the primary name and any nickname. This option currently is the only one where the preferred name is underlined, and is the only one to show nicknames (in &quot;quotes&quot;).'); ?>
    </li>
    <li><?= I18N::translate('Given and surnames'); ?> - <?= I18N::translate('like the full name, but without nicknames.'); ?></li>
    <li><?= I18N::translate('Given names'); ?> - <?= I18N::translate('just the given names are displayed.'); ?></li>
    <li><?= I18N::translate('First given name only'); ?> - <?= I18N::translate('just the first word of the name in the given names field.'); ?></li>
    <li><?= I18N::translate('Surnames'); ?> - <?= I18N::translate('just the surnames are displayed.'); ?></li>
    <li><?= I18N::translate('Initials only'); ?> - <?= I18N::translate('this displays initials only, for example &quot;JFK&quot;.'); ?></li>
    <li><?= I18N::translate('Given name initials and surname'); ?> - <?= I18N::translate('this shows initials for the first and second given name, as well as the full surname. For example: &quot;J.F. Kennedy&quot;'); ?>
    </li>
    <li><?= I18N::translate('Don\'t show names'); ?> - <?= I18N::translate('no names are shown. If birth and death details are also disabled then it is possible to show only photos or even just coloured boxes.'); ?>
    </li>
</ul>
<h5><?= I18N::translate('Abbreviated place names'); ?></h5>
<p>
    <?= I18N::translate('There are several options to shorten place names (for place of birth, place of marriage, place of death).'); ?>
</p>
<ul>
    <li><?= I18N::translate('Full place name'); ?> - <?= I18N::translate('the place name is printed in full.'); ?></li>
    <li><?= I18N::translate('City and country'); ?> - <?= I18N::translate('the first and last section of the place name is used, using commas to split the sections. For example, &quot;London, England, United Kingdom&quot; would be shortened to &quot;London, United Kingdom&quot;'); ?>
    </li>
    <li><?= I18N::translate('City and 2 letter ISO country code'); ?> - <?= I18N::translate('the first and last section of the place name is used, using commas to split the sections. The country is then converted to the ISO3166-1-Alpha-2 country code. <br>For example, &quot;Calgary, Alberta, Canada&quot; would be shortened to &quot;Calgary, CA&quot;'); ?>
    </li>
    <li><?= I18N::translate('City and 3 letter ISO country code'); ?> - <?= I18N::translate('the first and last section of the place name is used, using commas to split the sections. The country is then converted to the ISO3166-1-Alpha-3 country code.<br>For example, &quot;Calgary, Alberta, Canada&quot; would be shortened to &quot;Calgary, CAN&quot;'); ?>
    </li>
</ul>
<p>
    <?= I18N::translate('Note - The CLDR display name is used for matching. The data comes from <a href="https://www.datahub.io/core/country-codes" class="help-link">Datahub</a> but has been modified as for example the original CLDR name for the United Kingdom is &quot;UK&quot;, and the original CLDR name for the United States is &quot;US&quot;. Matching against these countries for the purposes of abbreviation is therefore pointless. So changes have been made to make this work better. Please <a href="https://github.com/Neriderc/GVExport/issues/new" class="help-link">open an issue</a> on GitHub if you find a country is not abbreviating correctly.'); ?>
</p>
<h5><?= I18N::translate('Abbreviated month names'); ?></h5>
<p>
    <?= I18N::translate('Selecting this box will shorten the month names. This uses the webtrees built in date shortening; in most cases, the month name will be shortened to three characters, e.g. \"Jan\" for January'); ?>
</p>
<h4><?= I18N::translate('Information on individuals'); ?></h4>
<h5><?= I18N::translate('Show individual XREF'); ?></h5>
<p>
    <?= I18N::translate('Whether to include the XREF of individuals in the diagram.'); ?>
</p>
<h5><?= I18N::translate('Show birthdate'); ?></h5>
<p>
    <?= I18N::translate('Check the box if you would like to include the birthdate of individuals in the output.'); ?>
</p>
<p>
    <?= I18N::translate('You can also choose whether to show the full date of birth or just the year.'); ?>
</p>
<h5><?= I18N::translate('Show birthplace'); ?></h5>
<p>
    <?= I18N::translate('Whether to show the place of birth in the output. Also see option for abbreviating place names.'); ?>
</p>
<h5><?= I18N::translate('Show death date'); ?></h5>
<p>
    <?= I18N::translate('Check the box if you would like to include the death date of individuals in the output.'); ?>
</p>
<p>
    <?= I18N::translate('You can also choose whether to show the full date of death or just the year.'); ?>
</p>
<h5><?= I18N::translate('Show death place'); ?></h5>
<p>
    <?= I18N::translate('Whether to show the place of death in the output. Also see option for abbreviating place names.'); ?>
</p>
<h5><?= I18N::translate('Show burial date'); ?></h5>
<p>
    <?= I18N::translate('Check the box if you would like to include the burial date of individuals in the output.'); ?>
</p>
<p>
    <?= I18N::translate('You can also choose whether to show the full date of burial or just the year.'); ?>
</p>
<h5><?= I18N::translate('Show burial place'); ?></h5>
<p>
    <?= I18N::translate('Whether to show the place of burial in the output. Also see option for abbreviating place names.'); ?>
</p>
<h5><?= I18N::translate('Show sex of individuals'); ?></h5>
<p>
    <?= I18N::translate('Whether to print the sex of the individual on the individual&apos;s tile, e.g. &quot;Male&quot;'); ?>
</p>
<h5><?= I18N::translate('Use similar events if information not available'); ?></h5>
<p>
    <?= I18N::translate('When showing information about a birth or death, if the information is not available then webtrees will look for similar events and use the information from those events instead.'); ?>
</p>
<ul>
    <li><?= I18N::translate('If a birth date or place is not recorded, webtrees will attempt to use the date or place of the christening or baptism if it exists.'); ?></li>
    <li><?= I18N::translate('If a death date or place is not recorded, webtrees will attempt to use the date or place of the burial or cremation if it exists.'); ?></li>
</ul>
<p>
    <?= I18N::translate('If you disable this option, GVExport will only use information from birth and death events, and not try to find missing information in similar events.'); ?>
</p>
<p>
    <?= I18N::translate('The options to show burial dates and places will use the burial or cremation events and is not affected by this setting.'); ?>
</p>
<h4><?= I18N::translate('Information on families'); ?></h4>
<h5><?= I18N::translate('Show family XREF'); ?></h5>
<p>
    <?= I18N::translate('Whether to include the XREF of families in the output.'); ?>
</p>

<h5><?= I18N::translate('Show only first marriage'); ?></h5>
<p>
    <?= I18N::translate('If a couple have been married more than once (a family record in webtrees has multiple marriage events), if this option is selected then only the first is shown (this is the default). If you unselect this option, all marriage events will be shown in the same family record in the diagram.'); ?>
</p>

<h5><?= I18N::translate('Show marriage date'); ?></h5>
<p>
    <?= I18N::translate('Check the box if you would like to include the date of marriage in the output.'); ?>
</p>
<p>
    <?= I18N::translate('You can also choose whether to show the full date of marriage or just the year.'); ?>
</p>
<h5><?= I18N::translate('Show marriage place'); ?></h5>
<p>
    <?= I18N::translate('Whether to show the place of marriage in the output. Also see option for abbreviating place names.'); ?>
</p>
<h5><?= I18N::translate('Show marriage type'); ?></h5>
<p>
    <?= I18N::translate('If selected, the type of marriage (civil, religious, registered partnership) will be shown on the family record.'); ?>
</p>
<h5><?= I18N::translate('Show when type not specified'); ?></h5>
<p>
    <?= I18N::translate('If selected, where the marriage type is not known then it will show a message stating this. If unselected, unknown marriage types will not be displayed.'); ?>
</p>
<p>
    <?= I18N::translate('Related links'); ?>:
</p>
<ul>
    <li><?= $help->getHelpLinkHtml(HELP::BROWSER_RENDER);?></li>
</ul>